### ISSUE TITLE
DATAFilter change for deletion of objects before insertion

### ISSUE THREAD

**Issue by kikanny** [3lvis/Sync#227]
Hey @3lvis! Sync is a great library and its helped out a lot to manage and sync data between our network fetches and core data. However, we've run into a small issue and was hoping for some feedback from you. 

We have an object that goes through various statuses during its lifecycle. Our API provides these objects in a paginated manner for a particular status. We specify which status and page we want using NSPredicate and pass it to Sync. However, the problem arises when the object has changed its status. Sync creates a new Core Data object instead of replacing/updating the old one that already exists in Core Data with the old status. The solution we are looking into rectifying this problem is to add an option in the DATAFilter library so that before an object is inserted into Core Data, a check is performed if an object with the same 'id' already exists without any predicates. If this object exists, it is deleted before inserting the object with the new status. Again, this wouldn't be the default behaviour but rather an option in Sync that would trigger this new behaviour. What do you think?

```objc
if (operations & DATAFilterOperationInsert) {
    for (id fetchedID in insertedObjectIDs) {
        NSDictionary *objectDictionary = remoteIDAndChange[fetchedID];
        if (inserted) {
            NSDictionary *dictionaryOldObjectIDs = [DATAObjectIDs objectIDsInEntityNamed:entityName
                                                                      withAttributesNamed:localPrimaryKey
                                                                                  context:context];
            NSManagedObjectID *oldObjectID = dictionaryOldObjectIDs[fetchedID];
            if (oldObjectID) {
                NSManagedObject *object = [context objectWithID:oldObjectID];
                if (object) {
                    NSLog(@"DATAFILTER DELETE BEFORE INSERT:- Fetched ID: %@", fetchedID);
                    [context deleteObject:object];
                }
            }
            NSLog(@"DATAFILTER INSERT:- Fetched ID: %@", fetchedID);
            inserted(objectDictionary);
        }
    }
}
```

**Comment by 3lvis** [comment]
Hi @kikanny

I'm happy that you have found this library useful, personally I use it in all my projects and I'm always happy to see that some use cases have already been solved thanks to the community.

Regarding your problem. I think this could be solved be removing the status from the NSPredicate that you send to Sync.

Is there a reason why that wouldn't work? Then Sync would just update those entries instead of making new ones. I hope you don't find dumb this question, just trying to understand the full scope of the problem to find different solutions.

Have a great weekend!

**Comment by kikanny** [comment]
Thanks for you reply @3lvis. If I don't pass the status and page predicates, Sync would update the existing objects like you said. However, it would also delete other entries that are not in this status or page. I've tested it without predicates and thats what seems to happen. I hope that made sense?

**Comment by 3lvis** [comment]
You could remove the predicate and to avoid objects being deleted you can limit the operations to Insert and Update.

```swift
Sync.changes(secondImport, inEntityNamed: "User", dataStack: dataStack, operations: [.Insert, .Update]) {
    // Here new users have been imported, existing users have been updated, and not found users have been ignored
}
```

That got implemented here: https://github.com/hyperoslo/Sync/pull/223

**Comment by 3lvis** [comment]
Closing this waiting for further response, last suggestion should fix the issue.

**Comment by kikanny** [comment]
Hi @3lvis ! Apologies for the really late reply. Got a bit busy! With regards to your suggestion about limiting the operations to Insert and Update, here's the problem. For example, if object A exists in the second page that we receive from the API and it doesn't exist any more in a consecutive call because the status has changed or the object has been removed, we would want to perform a delete operation for this object within that page.

**Comment by 3lvis** [comment]
I guess to summarize this, would be great if there was an option where, even when using a predicate, DATAFilter made sure that there's only one item for one id, and did a `insertOrUpdate` instead of the current behaviour.

**Comment by batjo** [comment]
Hi @3lvis I'm having the same issue and I think I found a way to fix this. The only thing is I'm not sure where I should add the `insertOrUpdate` parameter. First I though about adding an extra Operation but that doesn't play nice with the `.all` operation. But adding an extra argument to the sync function also doesn't seem a good idea. Any thoughts?

**Comment by 3lvis** [comment]
Hi @batjo! Any chance to get a failing unit test?

**Comment by batjo** [comment]
Of course, please have a look here: https://github.com/3lvis/Sync/tree/fix/227

**Comment by 3lvis** [comment]
What about something like this?

```swift
// https://github.com/3lvis/Sync/issues/227
func test227() {
    let dataStack = Helper.dataStackWithModelName("227")

    // Here the user wants to get all tags with status 0
    var tags = Helper.objectsFromJSON("227-status-0.json") as! [[String: Any]]
    let status0IDs = (tags as NSArray).value(forKey: "id") as? [Int] ?? [Int]()
    dataStack.sync(tags, inEntityNamed: "Tag", predicate: NSPredicate(format: "ANY id in %@", status0IDs), completion: nil)
    XCTAssertEqual(Helper.countForEntity("Tag", inContext: dataStack.mainContext), 1)

    // Now the user wants to get all tags with status 1, but meanwhile the status of Tag with id has changed to 1. 
    // Currently this creates a second tag object with the same ID
    tags = Helper.objectsFromJSON("227-status-1.json") as! [[String: Any]]
    let status1IDs = (tags as NSArray).value(forKey: "id") as? [Int] ?? [Int]()
    dataStack.sync(tags, inEntityNamed: "Tag", predicate: NSPredicate(format: "ANY id in %@", status1IDs), completion: nil)
    XCTAssertEqual(Helper.countForEntity("Tag", inContext: dataStack.mainContext), 1)
    let tag = Helper.fetchEntity("Tag", predicate: NSPredicate(format: "id = 1"), inContext: dataStack.mainContext).first
    let status = tag?.value(forKey: "status") as? Int
    XCTAssertEqual(status, 1)

    dataStack.drop()
}
```

Of course, this assumes that you either get an endpoint that returns objects just for a certain status or you do some preprocessing to remove objects with a certain status.

**Comment by batjo** [comment]
Thanks, this works indeed. 

Only thing that I still find hard is that currently I use an attribute called `synced` to determine if an object has local changes. If the object has local changes, I want to ignore updates from the backend on this object. Therefore I use the predicate but that generates duplicate primaryKeys (this issue). In my project the predicate would look like this:
```swift
NSPredicate(format: "ANY id in %@ AND synced == true", status0IDs)
```

But I guess in this situation I should just make sure to push all objects with localChanges first before requesting the list of objects from the server, right? Because now it would create new objects that have `synced == false`

**Comment by 3lvis** [comment]
@batjo I think pushing local elements first sounds like the most sensible approach to keep your local database always in sync.

**Comment by 3lvis** [comment]
Haven't seen any other issues related to this so might be an isolated case and not something related to the library, closing unless anything changes.
