### ISSUE TITLE
Add support for superentities with infinite levels

### ISSUE THREAD

**Issue by 3lvis** [3lvis/Sync#265]
Basically like https://github.com/hyperoslo/Sync/pull/264 but with support for more than one level.

**Comment by realtec** [comment]
I would love to see this implemented since I have the same issue while syncing deeper nested json from my API.
I'm ending up with duplicated records atm.
I can provide more information about the exact issue if needed.

**Comment by 3lvis** [comment]
@realtec that would be very useful, specially so I make sure to support your use case as well.

**Comment by realtec** [comment]
Alright here is my situation.
When sucessfully authenticated I want to fetch most of the user data in one call.
This is my data model:
<img width="559" alt="datamodel" src="https://cloud.githubusercontent.com/assets/1419576/19417698/c7c3e1ae-93b3-11e6-826d-19689c05aa1f.png">

My JSON response (I left out the timestamps for simplicity):
```json
{
  "id": 1,
  "email": "my@email.com",
  "players": [
    {
      "id": 1,
      "name": "Player 1",
      "game": {
        "id": 1,
        "name": "Game 1"
      },
      "player_group": {
        "id": 1,
        "name": "PlayerGroup 1",
        "players": [
          {
            "id": 2,
            "name": "Player 2",
            "game": {
              "id": 1,
              "name": "Game 1"
            }
          }
        ],
        "game": {
          "id": 1,
          "name": "Game 1"
        }
      }
    },
    {
      "id": 2,
      "name": "Player 2",
      "game": {
        "id": 1,
        "name": "Game 1"
      },
      "player_group": {
        "id": 1,
        "name": "PlayerGroup 1",
        "owner": {
          "id": 1,
          "name": "Player 1",
          "game": {
            "id": 1,
            "name": "Game 1"
          }
        },
        "players": [
          {
            "id": 1,
            "name": "Player 1",
            "game": {
              "id": 1,
              "name": "Game 1"
            }
          }
        ],
        "game": {
          "id": 1,
          "name": "Game 1"
        }
      }
    }
  ]
}
```

**Comment by 3lvis** [comment]
This was one of the most complex models so far :D

<img width="739" alt="screen shot 2016-12-01 at 21 12 09" src="https://cloud.githubusercontent.com/assets/1088217/20810671/e02f96ae-b80a-11e6-98ed-e402860de611.png">

**Comment by 3lvis** [comment]
The issue that you pointed out here @realtec is not really referred to what this issue was about, but I did found something :D

**Comment by 3lvis** [comment]
I believe this works fine in master.
