### ISSUE TITLE
Many-to-Many Relationships Null

### ISSUE THREAD

**Issue by norikachi** [3lvis/Sync#269]
HI 3lvis, I believe that is a bug in Many-to-Many relationships.

![screen shot 2016-08-22 at 9 08 33 am](https://cloud.githubusercontent.com/assets/4539108/18075665/29824fda-6eba-11e6-8f9e-c4de649400d2.png)

**First sync:** I get all speakers in session 1 and 2
![screen shot 2016-08-30 at 2 01 40 pm](https://cloud.githubusercontent.com/assets/4539108/18075687/5b6a261c-6eba-11e6-9d52-0bb1dd4fdb92.png)

But when the tableview reloaded (second sync), all speakers are gone. I expected that just only speakers in session 1 should be deleted. Speakers in session 2 should not be deleted.

When I restarted the app, I still could not get any speakers. I received this error message: 

"CoreData: warning: An NSManagedObjectContext delegate overrode fault handling behavior to silently delete the object with ID '0xd000000000140004 x-coredata://2D824DB1-6AFD-427B-90D3-EC789EDFEC86/Speaker/p5' and substitute nil/0 for all property values instead of throwing."

Thank you.

**Comment by teripaquitinho** [comment]
Hi @norikachi  I am experiencing the same issue... 

I managed to solve it by removing all empty arrays in the dictionary before passing it to the sync function... 

```var data: Array<[String : Any]>? = nil
for element in originalData {
  data.append(element.emptyRemoved)
}
Sync.changes(data, inEntityNamed: myEntity, dataStack:myDataStack) 
```

where  `emptyRemoved` is placed within an extension for `Dictionary` as suggested here http://stackoverflow.com/a/35787010

```    var emptyRemoved: [Key: Any] {
        let tup = filter {
            //if let detailsDict = details as? NSDictionary
            if let element = $0.1 as? Array<Any> {
                return !element.isEmpty
            }
            return !($0.1 is NSNull)
        }
        return tup.reduce([Key: Value]()) { $0.0.updatedValue($0.1.value, forKey: $0.1.key) }
    }
```

Did you find a better solution for this?

@3lvis i believe this should be the default behaviour for this case but maybe this can also be a param

**Comment by 3lvis** [comment]
A proposed fix was submitted here, please give it a try and let me know if there are any issues: https://github.com/3lvis/Sync/pull/418

Thanks for you patience <3
