### ISSUE TITLE
Regression: Crash when Syncing json array with models who refer to each other by ids 

### ISSUE THREAD

**Issue by neil-morrison44** [3lvis/Sync#353]
Hi,

I've got a json API which is a format similar to:

```json
[{
"id": 1,
"relationshipAIds": [2, 3], 
"relationshipBIds": [2]
},
{
"id": 2,
"relationshipAIds": [1, 3], 
"relationshipBIds": [1, 2]
},
{
"id": 3,
"relationshipAIds": [2], 
"relationshipBIds": [1, 2]
}  ]
```

That is - relationshipA is the inverse of relationship B.
In my Core Data setup they're setup as an ordered set with the same inverse relationship.

Previously Sync handled this fine, it'd output warnings to the log when it parsed an element which referred to elements which had not been parsed yet - but when it would get to those elements because the relationship is an inverse it'd correctly tie everything together.

However, I updated Sync to pull in the new update/insert API methods and I'm getting crashes the stacktrace of which terminates at:

https://github.com/SyncDB/Sync/blame/c5db4be861e5adccfff4abbcdc7d20b983535756/Source/Sync/NSManagedObject%2BSync.swift#L157

with something like
```
*** Terminating app due to uncaught exception 'NSRangeException', reason: '*** -
[NSMutableOrderedSet moveObjectsAtIndexes:toIndex:]: index 6 
beyond bounds [0 .. 4]'
```

- I can probably get around this problem by making my relationship unordered (since I don't strictly need ordering)

Let me know if you need any more information

**Comment by 3lvis** [comment]
Hi @neil-morrison44,

Thanks for reporting this issue. Is most likely that this was introduced in https://github.com/SyncDB/Sync/pull/328.

Matching with ids, has a few caveats, one of this is that is ideal that the objects that you reference by id are already in Core Data. Otherwise, it might work sometimes, meaning, it will work only if the entity is already there.

**Comment by 3lvis** [comment]
I think adding a safety check to silently fail instead of crashing might be the solution for this.

**Comment by 3lvis** [comment]
This shouldn't be a problem anymore.
