### ISSUE TITLE
Many to Many where the linking file is new.

### ISSUE THREAD

**Issue by jimijon** [3lvis/Sync#356]
Wondering if this is covered.

I have a set of Stores. I have a set of Products. 
The Products are fully populated.

When syncing a store, I also pull in the storeProducts in the JSON. Inside the JSON for storeProducts there is a productCode.

Can the relationship between storeProduct -> Product be created. Or do I have to process these records afterwards to fetch the product and create the relationship in CoreData.

Thanks

**Comment by MojtabaHs** [comment]
Yes, if you set productCode as primary key in Product entity and storeProduct is a relation.

**Comment by jimijon** [comment]
Hmmm, in my storeProduct table I have productNFCode. This points to nfCode in my Product table.

Is there a way to tell Sync to use productNFCode and map it to nfCode?

**Comment by jimijon** [comment]
I just tried making hyper.remoteKey = "nfCode" to no avail.

**Comment by MojtabaHs** [comment]
This will done by setting primary key and remote key automatically. Perhaps a look on your data model and a sample of JSON response could help to resolve your issue faster ;)

**Comment by jimijon** [comment]
As requested:

<img width="613" alt="screen shot 2017-01-11 at 12 06 02 pm" src="https://cloud.githubusercontent.com/assets/971445/21860504/82dc00ee-d7f6-11e6-9e84-43accc5353d8.png">

`{
      "id": "1",
      "sectionKey": "S",
...

      "announcements": "",
      "lastUpdate": "2017-01-05 02:02:37",
      "nfCode": "5sqf",
      "storeProducts": [
        {
          "id": "2",
          "storeNFCode": "5sqf",
          "productNFCode": "nj8g3",
          "lastUpdate": "2017-01-05 02:03:37"
        },
        {
          "id": "6",
          "storeNFCode": "5sqf",
          "productNFCode": "4889v",
          "lastUpdate": "2017-01-05 02:03:37"
        },
        {
          "id": "9",
          "storeNFCode": "5sqf",
          "productNFCode": "8rfm3",
          "lastUpdate": "2017-01-05 02:03:37"
        },
        ...`

**Comment by 3lvis** [comment]
It's been sometime after this issue was opened, let's open a new one if it's still relevant.
