### ISSUE TITLE
Lazy relation ?

### ISSUE THREAD

**Issue by MojtabaHs** [3lvis/Sync#357]
Hey

I have a situation here that relations are lazy.

take a look at this please: 

```
{
    "id" : 1,
    "name" : "a",
    "relations" : {
        { 
            "id" : 10,
            "name" : "M"
        }
    }
}
```

later on...

```
{
    "id" : 1,
    "name" : "a",
    "relations" : {
        { 
            "id" : 20,
            "name" : "H"
        }
    }
}
```

on syncing this, the previous relation deletes and this is not excepted.

The exception will be:

```
{
    "id" : 1,
    "name" : "a",
    "relations" : {
        { 
            "id" : 20,
            "name" : "H"
        },
        { 
            "id" : 10,
            "name" : "M"
        }
    }
}
```

Any suggestions ?

**Comment by 3lvis** [comment]
Hi @MojtabaHs,

If you sync the second JSON, of course it will replace the contents of the first one, that's how Sync works. It diffs the local with the remote and acts on it.

If you want to keep the old contents try using only insert and update. Something like this:

```swift
Sync.changes(secondImport, inEntityNamed: "User", dataStack: dataStack, operations: [.Insert, .Update]) { _ in
}
```

I hope this fixes your problem, otherwise just let me know. :)

**Comment by MojtabaHs** [comment]
Operations are .Insert and .Update already. @3lvis I check this things before posting here ;) 
Dude, Don't close issues without confirm of opener too fast.

**Comment by 3lvis** [comment]
@MojtabaHs There's no issue in reopening if the problem is not fixed. Could you post your Core Data model, please? Wanna check out if it's a many-to-many relationship or just to-many.

**Comment by MojtabaHs** [comment]
It's meny to meny @3lvis. Setting operations only works on main object I think. Nested objects not respecting to it. I double checked.

**Comment by 3lvis** [comment]
It's been sometime after this issue was opened, let's open a new one if it's still relevant.
