### ISSUE TITLE
Update issues

### ISSUE THREAD

**Issue by vito-royeca** [3lvis/Sync#359]
I have a many-to-many relationship between two entities. The app runs ok for about a day , but when it is run again the next day it encounters this error behaviour:

*** Terminating app due to uncaught exception 'NSRangeException', reason: '*** -[NSMutableOrderedSet moveObjectsAtIndexes:toIndex:]: index 6 beyond bounds [0 .. 1]'
*** First throw call stack:
(
	0   CoreFoundation                      0x0000000103dddd85 __exceptionPreprocess + 165
	1   libobjc.A.dylib                     0x0000000106c02deb objc_exception_throw + 48
	2   CoreFoundation                      0x0000000103e2b49b -[NSMutableOrderedSet moveObjectsAtIndexes:toIndex:] + 971
	3   CoreData                            0x000000010754c335 -[_NSNotifyingWrapperMutableOrderedSet moveObjectsAtIndexes:toIndex:] + 117
	4   Sync                                0x00000001051157f3 _TFE4SyncCSo15NSManagedObject23sync_toManyRelationshipfzTCSo25NSRelationshipDescription10dictionaryGVs10DictionarySSP__6parentGSqS0__18parentRelationshipGSqS1__7contextCSo22NSManagedObjectContext10operationsVCS_4Sync16OperationOptions19shouldContinueBlockGSqFT_Sb_15objectJSONBlockGSqFGS2_SSP__GS2_SSP____T_ + 21763
	5   Sync                                0x000000010510ee21 _TFE4SyncCSo15NSManagedObject9sync_fillfT4withGVs10DictionarySSP__6parentGSqS0__18parentRelationshipGSqCSo25NSRelationshipDescription_7contextCSo22NSManagedObjectContext10operationsVCS_4Sync16OperationOptions19shouldContinueBlockGSqFT_Sb_15objectJSONBlockGSqFGS1_SSP__GS1_SSP____T_ + 4225
	6   Sync                                0x0000000105132084 _TFZFC4Sync4Sync7changesFzTGSaGVs10DictionarySSP___13inEntityNamedSS9predicateGSqCSo11NSPredicate_6parentGSqCSo15NSManagedObject_18parentRelationshipGSqCSo25NSRelationshipDescription_9inContextCSo22NSManagedObjectContext10operationsVS0_16OperationOptions19shouldContinueBlockGSqFT_Sb_15objectJSONBlockGSqFGS1_SSP__GS1_SSP____T_U0_FTGS1_SSP__S3__T_ + 564
	7   Sync                                0x0000000105132322 _TPA__TFZFC4Sync4Sync7changesFzTGSaGVs10DictionarySSP___13inEntityNamedSS9predicateGSqCSo11NSPredicate_6parentGSqCSo15NSManagedObject_18parentRelationshipGSqCSo25NSRelationshipDescription_9inContextCSo22NSManagedObjectContext10operationsVS0_16OperationOptions19shouldContinueBlockGSqFT_Sb_15objectJSONBlockGSqFGS1_SSP__GS1_SSP____T_U0_FTGS1_SSP__S3__T_ + 242
	8   Sync                                0x000000010510a953 _TZFC4Sync10DATAFilter7changesfTGSaGVs10DictionarySSP___13inEntityNamedSS9predicateGSqCSo11NSPredicate_10operationsVS0_9Operation15localPrimaryKeySS16remotePrimaryKeySS7contextCSo22NSManagedObjectContext8insertedFGS1_SSP__T_7updatedFTGS1_SSP__CSo15NSManagedObject_T__T_ + 7187
	9   Sync                                0x0000000105130d92 _TZFC4Sync4Sync7changesfzTGSaGVs10DictionarySSP___13inEntityNamedSS9predicateGSqCSo11NSPredicate_6parentGSqCSo15NSManagedObject_18parentRelationshipGSqCSo25NSRelationshipDescription_9inContextCSo22NSManagedObjectContext10operationsVS0_16OperationOptions19shouldContinueBlockGSqFT_Sb_15objectJSONBlockGSqFGS1_SSP__GS1_SSP____T_ + 3218
	10  Sync                                0x000000010512fd1b _TZFC4Sync4Sync7changesfTGSaGVs10DictionarySSP___13inEntityNamedSS9predicateGSqCSo11NSPredicate_6parentGSqCSo15NSManagedObject_18parentRelationshipGSqCSo25NSRelationshipDescription_9inContextCSo22NSManagedObjectContext10operationsVS0_16OperationOptions10completionGSqFGSqCSo7NSError_T___T_ + 603
	11  Netzkino                            0x0000000103527e0c _TTSf2n_n_i_n_n_n___TFFFC8Netzkino3API14fetchFrontpageFGSqFGSqCSo7NSError_T__T_U_FTGSaGVs10DictionarySSP___GSqS1___T_U_FCSo22NSManagedObjectContextT_ + 956
	12  Netzkino                            0x00000001035512b1 _TPA__TTSf2n_n_i_n_n_n___TFFFC8Netzkino3API14fetchFrontpageFGSqFGSqCSo7NSError_T__T_U_FTGSaGVs10DictionarySSP___GSqS1___T_U_FCSo22NSManagedObjectContextT_ + 177
	13  DATAStack                           0x00000001045b08e3 _TFFC9DATAStack9DATAStack29performInNewBackgroundContextFFCSo22NSManagedObjectContextT_T_U_FT_T_ + 67
	14  DATAStack                           0x00000001045b0927 _TTRXFo___XFdCb___ + 39
	15  CoreData                            0x000000010743f127 developerSubmittedBlockToNSManagedObjectContextPerform + 199
	16  libdispatch.dylib                   0x0000000108f673eb _dispatch_client_callout + 8
	17  libdispatch.dylib                   0x0000000108f4d82c _dispatch_queue_drain + 2215
	18  libdispatch.dylib                   0x0000000108f4cd4d _dispatch_queue_invoke + 601
	19  libdispatch.dylib                   0x0000000108f4f996 _dispatch_root_queue_drain + 1420
	20  libdispatch.dylib                   0x0000000108f4f405 _dispatch_worker_thread3 + 111
	21  libsystem_pthread.dylib             0x00000001092a4712 _pthread_wqthread + 1299
	22  libsystem_pthread.dylib             0x00000001092a41ed start_wqthread + 13
)
libc++abi.dylib: terminating with uncaught exception of type NSException
(lldb)

**Comment by 3lvis** [comment]
@jovito-royeca Could you share your Core Data file and JSON file to reproduce the issue? It seems like something related to update operations.

**Comment by jovito-royeca** [comment]
Hi Elvis,

Attached are the [SQLite data files](https://github.com/SyncDB/Sync/files/716610/sqlite.zip),  
[Core Data model](https://github.com/SyncDB/Sync/files/716616/Netzkino.xcdatamodeld.zip), and  [JSON data](https://github.com/SyncDB/Sync/files/716612/data.json.zip). Everytime the app starts, the json is downloaded from server and then inserted to Core Data via SyncDB:

`self.dataStack.performInNewBackgroundContext { backgroundContext in
                   var newData = [[String : Any]]()
                   // newData will be populated with JSON from server, as well as some internal data

                    Sync.changes(newData, inEntityNamed: "Category", predicate: nil, parent: nil, parentRelationship: nil, inContext: backgroundContext, operations: .All, completion:  { error in
                        // error goes here...    app crashes
                    })
                }`

Thank you for looking into this issue.

- Jovito

**Comment by 3lvis** [comment]
Thanks <3, I'll have a look when I've got some time.

**Comment by cannaz** [comment]
some news about this issue? I have the same problem when I restart the app and I import the same json. Thanks

**Comment by jovito-royeca** [comment]
I was able to fix the error by modifying the one-to-many relationship arrangement from Ordered to Not Ordered.

**Comment by Lailan** [comment]
Thanks @jovito-royeca 
This reply solved to me too!

**Comment by 3lvis** [comment]
I'll double check the issue with the ordered relationship but in general Sync works better with not ordered since that's what I use :(.

**Comment by 3lvis** [comment]
Thanks for your support in this library. It has been a while since I used CoreData in any of my projects and it's hard for me to maintain this library. If you have been part of the Sync contributors group and want to take ownership of the library let me know to elvisnunez@me.com. For now, I'll be archiving this library.
