### ISSUE TITLE
Delete Operation for related items

### ISSUE THREAD

**Issue by jimijon** [3lvis/Sync#360]
I am syncing a product with its images.

I never want sync to delete the products.
I Do want sync to delete the images if they don't exist.

Is this possible on one pass?

**Comment by 3lvis** [comment]
@jimijon Maybe something like this:

```swift
let listOfProducts = // the array of JSON recipes
for jsonProduct in listOfProducts {
    try! Sync.insertOrUpdate(jsonProduct, inEntityNamed: Product.entityName, using: backgroundContext)
}
```

**Comment by jimijon** [comment]
In your response you have "jsonProduct", which I assume contains a relationship with a list of jsonImages. How will the insertOrUpdate delete images?

How about a switch in the userInfo table/relationship for insert, update, delete?

**Comment by 3lvis** [comment]
Actually, I think this should work

```swift
Sync.changes(products, inEntityNamed: "Product", dataStack: dataStack, operations: [.Insert, .Update]) { error in
    //..
}
```

**Comment by 3lvis** [comment]
Would you mind sharing your Core Data model and JSON if that doesn't work? I can double check what's going on.

**Comment by 3lvis** [comment]
It's been sometime after this issue was opened, let's open a new one if it's still relevant.
