### ISSUE TITLE
Managing Sync Using an Operation is Never Marked Finished

### ISSUE THREAD

**Issue by rlester** [3lvis/Sync#366]
In a project I am working on we are using an OperationQueue to manage the max number of concurrent operations since much of the syncing must be serial.

``` swift
let operation = Sync(changes: [representation], inEntityNamed: String(describing: self), predicate: nil, dataStack: dataStack, operations: self.objectFilterOperation)
            operation.completionBlock = {
                if operation.isFinished {
                    success()
                } else {
                    failure(NSError.init(domain: "ResponseSerializableObject", code: -1, userInfo: nil))
                }
            }
self.serializationQueue.addOperation(operation)
````

I am noticing that the operations are never marked as completed. After looking through the code I noticed that ```updateFinished```  is only called if an operation is [cancelled](https://github.com/SyncDB/Sync/blob/master/Source/Sync/Sync.swift#L88) or an operation has an [error](https://github.com/SyncDB/Sync/blob/master/Source/Sync/Sync.swift#L114). I believe one is missing for the case when when the syncing is [successful](https://github.com/SyncDB/Sync/blob/master/Source/Sync/Sync.swift#L108).

My question is if I am using sync incorrectly or if this truly is a bug. If its a bug I would be more than happy to resolve, just wanted to be sure I wasn't abusing the library first.

**Comment by 3lvis** [comment]
Hi @rlester, 

Darn, I need to double check what's going on in there. Thanks for reporting this issue!

**Comment by tcordoba** [comment]
Hi,
I'm having the same issue here. Any update regarding this problem?
Thanks
Regards

**Comment by 3lvis** [comment]
Haven't had the chance to look into it, but might be related to the operation status not being set properly internally.

**Comment by tcordoba** [comment]
Hi, 
I think I have fixed the issue. I have added `self.updateFinished(true)` to the file Sync.swift. I you found this correct let me know and I will push the code to the repository.

`    func perform(using context: NSManagedObjectContext) {
        do {
            try Sync.changes(self.changes, inEntityNamed: self.entityName, predicate: self.predicate, parent: self.parent, parentRelationship: self.parentRelationship, inContext: context, operations: self.filterOperations, shouldContinueBlock: { () -> Bool in
                
                return !self.isCancelled
            }, objectJSONBlock: { objectJSON -> [String: Any] in
                
                return self.delegate?.sync(self, willInsert: objectJSON, in: self.entityName, parent: self.parent) ?? objectJSON
            })
            self.updateFinished(true)
        } catch let error as NSError {
            print("Failed syncing changes \(error)")

            self.updateExecuting(false)
            self.updateFinished(true)
        }
    }`

**Comment by rlester** [comment]
@tcordoba I tried out your changes and it seems to resolve the issue only my side. Mind open a pull request?
