### ISSUE TITLE
relationships get deleted when syncing Many-To-Many objects

### ISSUE THREAD

**Issue by teripaquitinho** [3lvis/Sync#373]
Hi 3lvis, 

First of all congrats on the great job you did with this library. I'm currently facing a problem and as I'm trying to sync elements which have a many to many relationship. The data model looks like this:

<img width="351" alt="screen shot 2017-02-27 at 17 34 56" src="https://cloud.githubusercontent.com/assets/483501/23369894/2591de4e-fd13-11e6-92d9-e1acc7d4512e.png">

*NOTE* that in my case the `id` fields for all books and authors are string

Given a JSON `bookData` that looks like the following:
```[
  {
    "id": "1",
    "title": "Book 2",
    "abstract": "abstract for book 1",
    "author": [
      {
        "id":3143,
        "name":"John"
      }, {
        "id":3144,
        "name":"Sam"
      }
    ]
  },
  {
    "id": "2",
    "title": "Book 2",
    "abstract": "abstract for book 2",
    "author": [
      {
        "id":3143,
        "name":"John"
      }
    ]
  }
]
```

What i'm doing is:

```
Sync.changes(booksData!, inEntityNamed: "Book", dataStack: mydataStack) 
```

From what I see, at first, the 1st book is correctly created with both authors, but when the second book it's also created the relationship between JOHN and BOOK1 gets deleted and replaced by a new one for JOHN and BOOK2

So when I fetch the first book from CoreData i just get one author... Can you help? I saw it is possible to map arrays or dictionaries by setting `Binary Data` on the Core Data model, but I would really not go down that road... I really feel i'm missing something here...

Thanks a lot

**Comment by teripaquitinho** [comment]
@3lvis I found it... apparently if I create an entity with the attribute `id` being a `String` the mapping for the reverse relationship does not work properly... Now I changed my configuration to accept `id` being a `Integer32` and everything works.

**Comment by rhelba** [comment]
I have been banging my head on what looks to be the same issue for the past couple of days as well. Is there an upcoming fix for this? If not, will have to look for alternatives – switching to `Integer 32` ids is not an option at this stage in the project. Otherwise I'm really impressed with the Sync library, so would prefer to use it going forward as well. Thanks for your efforts, @3lvis!

**Comment by andersblehr** [comment]
I ended up rolling my own framework to work around this: [andersblehr/JSONCache](https://github.com/andersblehr/JSONCache). Some overlap with Sync, with some added features that I felt were missing, such as producing JSON for persisting data to the backend.

**Comment by 3lvis** [comment]
Hi @andersblehr, 

I'm glad Sync helped you getting started in open sourcing your work! Looking forward to borrowing some features back :)

If you ever feeling like contributing back you're completely welcome.

**Comment by andersblehr** [comment]
Thanks, @3lvis – borrow away :)

**Comment by 3lvis** [comment]
@andersblehr Btw, it is possible to produce JSON out of NSManagedObjects https://github.com/SyncDB/Sync#json-exporting.

**Comment by andersblehr** [comment]
Cheers for the pointer. I did look into this. The primary reason for moving away from Sync was the above bug, not lack of JSON generation features. That said, I spun my own JSON generation anyhow, as our workflow is to only persist ('cache') objects to Core Data once they had been secured – and been assigned an id – on the backend. I considered instantiating temporary `NSManagedObject` instances exactly for the purpose of letting Sync generate JSON from them, but then having to delete them (alternatively update them with the id when the backend call returned) did not sit well in my head with the semantics of the workflow: Save first (i.e., to the backend), then cache (i.e., to Core Data).

**Comment by 3lvis** [comment]
A proposed fix was submitted here, please give it a try and let me know if there are any issues: https://github.com/3lvis/Sync/pull/418

Thanks for you patience <3
