### ISSUE TITLE
[Feature request] Add support for deep mapping for relationships

### ISSUE THREAD

**Issue by 3lvis** [3lvis/Sync#387]
- [x] to-many (fixed in https://github.com/SyncDB/Sync/pull/385)
- [ ] to-one
- [ ] to-many simplified
- [ ] to-one simplified

**Comment by mzgnr** [comment]
Hi @3lvis do you need any help for this issue? I would like to implement to-one for one of my projects.

**Comment by 3lvis** [comment]
@mzgnr Help on this would be fantastic! Should be similar than https://github.com/SyncDB/Sync/pull/385 but in this method instead.

https://github.com/SyncDB/Sync/blob/master/Source/Sync/NSManagedObject%2BSync.swift#L328

**Comment by 3lvis** [comment]
I believe this should be fixed now in master.
