### ISSUE TITLE
Dropping memoryStack doesn't recreate persistentStore

### ISSUE THREAD

**Issue by Zarakas** [3lvis/Sync#398]
Hey,

in the current version of Sync 3.2.3 dropping a memoryStack via "drop()" results in a DataStack without persistentStore:

**Illegal attempt to save to a file that was never opened. "This NSPersistentStoreCoordinator has no persistent stores (unknown).  It cannot perform a save operation.". No last error recorded.**

Even if I use the completion block an perform mein new inserts after it fires, same result.

Sometimes we need the drop to make sure we have only the case specific data in our memoryStack.

Greetz,

Zarak

**Comment by 3lvis** [comment]
Hi @Zarakas,

In what iOS version are you?

**Comment by Zarakas** [comment]
Hey @3lvis ,

version is iOS 10.3.2

**Comment by kleber11** [comment]
I have the same error. Any ideas?

**Comment by 3lvis** [comment]
@kleber11 could you try this branch? `fix/persistent-store-not-recreating`

https://github.com/3lvis/Sync/pull/423

**Comment by kleber11** [comment]
@3lvis thanks. It works perfectly! :)

**Comment by 3lvis** [comment]
I'll make a new release with that feature then :)

**Comment by 3lvis** [comment]
https://github.com/3lvis/Sync/releases/tag/3.3.1
