### ISSUE TITLE
Take too long for saving change to local db

### ISSUE THREAD

**Issue by jetstar89** [3lvis/Sync#400]
Hi 3lvis,
I am using SyncDB, in some cases it takes 7-10 seconds to finish saving change.
Is there any way to reduce saving time?
Thanks and Regards,

**Comment by 3lvis** [comment]
Hi @jetstar89,

I hope you're having a nice weekend :) Can I get some more information in the operation that you're doing? Having your Core Data model and an example of your JSON file might help a lot to profile the save.

Also, is it blocking your main thread or you don't have problems with that?

**Comment by jetstar89** [comment]
Hi 3lvis, It isn't blocking my main thread, cos I save in background thread.
But it takes quite much time for completion.

**Comment by 3lvis** [comment]
@jetstar89 Could you help me providing an example project I can use to reproduce this issue?

Thanks in advance :)

**Comment by jetstar89** [comment]
Hi 3lvis, could we have a private channel, Like slack, skype or any thing else.
Regards,

**Comment by 3lvis** [comment]
@jetstar89 you can write me in a privat channel in https://gitter.im/SyncDB/Sync

**Comment by 3lvis** [comment]
Haven't seen any other issues related to this so might be an isolated case and not something related to the library, closing unless anything changes.
