### ISSUE TITLE
Mapping for one to many Simplified 

### ISSUE THREAD

**Issue by methebao** [3lvis/Sync#401]
Hi man,
I have this json and I model my database : 
 + regions : Region entity 
 + cities: City Entity
When mapping, I mapped Regions, cities successfully. But I do not know how to map through ID ( like region_id ) . It mean when I have a key with array of Integer. How to create relationships, how to like this id to each entity. 

JSON: 

> "regions": [
>     {
>       "id": 1,
>       "name": "Đồng bằng Sông Hồng",
>       **"cities":** [
>         {
>           "id": 1,
>           "name": "Hà Nội",
>           **"region_id"**: 1,

**Comment by 3lvis** [comment]
Hi @methebao,

Gonna try to check it out soon, shouldn't be hard to implement. :)

**Comment by alijaza** [comment]
Pinging for an update on this, if you have one @3lvis. Thanks!

**Comment by 3lvis** [comment]
For the record: this should be possible, check the tests for `test375toOneSimplified`

https://github.com/3lvis/Sync/issues/375
