### ISSUE TITLE
OSX

### ISSUE THREAD

**Issue by webersson** [3lvis/Sync#403]
Could anyone tell me how to setup Sync on a OS X project?
How to set the AppDelegate File?

I´m trying for days no.
There is no tutorial to be found.

Thank you so much!

**Comment by 3lvis** [comment]
Sadly, I haven't had enough time to work on this, if anyone else would like to look into it I'll be happy to provide support. In my opinion should be straightforward to have a demo using NSFetchedResultsController.

**Comment by 3lvis** [comment]
Closing this for now, Sync should work on all the platforms, sadly at this time, I won't be able to find the time to work on making an example for macOS.
