### ISSUE TITLE
Sync JSON very very very too long

### ISSUE THREAD

**Issue by MicMat68** [3lvis/Sync#405]
Hi,

One model, 7 entities, many relationships, 100,000 rows max, but between 15 and 25 minutes for init core data...
I check id, index, but i don't understand why.
I receive JSON from firebase.

What i have to check? (sorry my english)

Edit : problems grows up with many relationships. For an entity with 300 000 rows, more one hour to sync...

**Comment by MicMat68** [comment]
I think json structure firebase has a part of responsability.

Relationships one-to-many simplified with format :
attributs :
-key_firebase1: true
-key_firebase2: true

**Comment by 3lvis** [comment]
@MicMat68 Wow, that's a lot of data. I think using plain Core Data the issue would be similar, not sure if it's something Sync related.

**Comment by MicMat68** [comment]
After the first init, it's work fine.
I will preload data in app, but for development, it's painful.

With 2 entities and a relationship on-to-many, it's work fine, but with a third entity, it's very increasing...

**Comment by 3lvis** [comment]
:( not sure what we can do about it. 300 000 could be considered an edge case.

**Comment by 3lvis** [comment]
Closing since this should be considered an edge case. Sorry for that.
