### ISSUE TITLE
Upgraded to 3x from 2x: Relationships aren't being created.

### ISSUE THREAD

**Issue by jimijon** [3lvis/Sync#408]
I have that edge case where I use my own "code" for all primary indexes. Hence the use of hyper.isRemoteKey and hyper.remoteKey.

It worked fine in the 2 version and now it doesn't create the relationships in the 3 version.

**Comment by 3lvis** [comment]
Hi @jimijon,

Could you help me giving some information or sample project to reproduce your issue? Thanks!

**Comment by jimijon** [comment]
Well it's pretty big application, etc. With the v3 it seems to import records but something goes awry and the relationships are not there, plus other weirdness. Are you sure v3 works well with"

hyper.isRemoteKey
hyper.remoteKey 

in all my records?

I also noticed it went from DATAStack to DataStack. Maybe something there?

**Comment by 3lvis** [comment]
@jimijon all the old tests are still passing so nothing broke as far as I was concerned =/

**Comment by jimijon** [comment]
do your tests only use a string key? And not an id or remoteId ?

**Comment by 3lvis** [comment]
Hi! The current tests test pretty much everything.

Sync Tests:
https://github.com/SyncDB/Sync/blob/master/Tests/Sync/SyncTests.swift

Entire tests folder:
https://github.com/SyncDB/Sync/tree/master/Tests

**Comment by jimijon** [comment]
Where in the tests do you read the user info settings?

**Comment by 3lvis** [comment]
That's included in the Core Data model, for example here.

<img width="1364" alt="screen shot 2017-06-30 at 08 41 57" src="https://user-images.githubusercontent.com/1088217/27724003-032ddf0c-5d70-11e7-9b8c-dc930c6b8d76.png">

**Comment by jimijon** [comment]
Ok see the model.

How come there are two user info remoteKeys?

a) current —>   sync.remoteKey
b) old        —> hyper.remoteKey

Won’t these interfere? Does it make a difference using “hype” or “sync” ?   I have been using hyper.


ALSO:

There is no “hyper.isPrimaryKey” for “current”.


Thoughts?
James

**Comment by 3lvis** [comment]
Have a look at the tests, please, I believe the problem might be something else. Having a failing unit test or a project to reproduce this issue would help a lot to get it fixed. Thanks and sorry for taking so long in replying :)

**Comment by 3lvis** [comment]
Haven't seen any other issues related to this so might be an isolated case and not something related to the library, closing unless anything changes.
