### ISSUE TITLE
Mapping issues with JSON

### ISSUE THREAD

**Issue by alijaza** [3lvis/Sync#411]
Hello, I have a relatively straightforward model with two entities: conversations and messages

Each conversation has a "To Many" relationship with messages. When I fetch the conversations, the JSON response includes some data about the "lastMessage" of the conversation as follows:

```
“conversations” : [{
"id" : “111222333”,
"read" : false,
“candidateId" : “1234”,
"customerId" : “6789”,
"candidateName" : “John Doe“,
"userName" : “johndoe@abc.com",
"lastMessage" : {
"messageId" : “9876”,
"messageText" : “What’s up”,
"time" : "2017-07-15T00:50:57Z"
}
}]

"messages": [
{
"id": “9876”,
"customerId": "6789",
"userName": "johndoe@abc.com",
"phoneNumber": "+15551112222”,
"candidateId": “1234”,
"candidateName": “John Doe“,
"status": "read",
"messageText": "What’s up",
"time": "2017-07-15T00:50:57Z",
“conversationId”: "111222333"
}]
```

I'm having trouble with two issues: 

(1) messages are returned with a remoteKey of 'id' while the 'lastMessage' uses 'messageId'. Do these have to be consistent in order to use Sync?

(2) The bigger issue is that I need a way to map the 'lastMessage' into messages since it is not returned as a set of messages (only one) and since the key value is 'lastMessage' which doesn't match the 'messages' relationship.

**Comment by 3lvis** [comment]
Hi @alijaza,

You could have a relationship like this:

`Conversation` has many `messages`
`Conversation` has one `lastMessage`

Here messages and last message are two different entities.

**Comment by alijaza** [comment]
Thanks for the quick reply. I thought about this solution but I see two issues:
(i) My messages responses have the usual key 'id' while the lastMessage has a different key ('messageId'). Any way to handle this without an API update?
(ii) I would have to update the 'lastMessage' attribute every time a new message comes in. Any way to avoid this and read this directly into the 'conversation.messages' set?

**Comment by 3lvis** [comment]
@alijaza I'm afraid Sync doesn't support your use case out of the box, I would suggest you pre-process your JSON in your app so it fits with what's expected by Sync or roll your own implementation based on the basic Sync functionality. Sorry for not being more helpful.

**Comment by alijaza** [comment]
Thanks @3lvis for your quick replies and also for this awesome tool. One more issue I came across is that my data comes paginated in sets of 20 results at a time. Sync's default behavior when including deletes seems to erase all of my objects except the current page of data. Is there any way for Sync to handle deletes only in the case that they are somehow (?) marked for deletion (and NOT delete all objects that are not in the current page of results? In other words, how can Sync be used with paginated data?

**Comment by 3lvis** [comment]
Hi @alijaza,

I believe you could achieve this by using the predicate, the predicate tells Sync which items should use for the diffing part, for example if you have 100 local items you could tell sync to avoid syncing with those elements. I don't have a demo project for that right now but that should work.

**Comment by alijaza** [comment]
@3lvis, I used predicates and things are working great! Yet another issue has arisen though (sorry!). Somehow my related objects are being created for each new object, but they aren't being created for an existing object. In other words, given the following JSON:

```
“conversations” : [{
"id" : “111222333”,
"read" : false,
“candidateId" : “1234”,
"customerId" : “6789”,
"candidateName" : “John Doe“,
"userName" : “johndoe@abc.com",
"messages" : [{
"id" : “9876”,
"messageText" : “What’s up”,
"time" : "2017-07-15T00:50:57Z" }]
}]
```

It seems if the conversation already exists but the related "message" does not exist, Sync doesn't create the message (?). I could be wrong about this, but can you confirm if this is intended behavior and how I can force the related objects to be created when the parent object already exists? Thank you!
