### ISSUE TITLE
Missing PrimaryKey causes error evaluating nil

### ISSUE THREAD

**Issue by allemattio** [3lvis/Sync#412]
Hi,
I'm doing some error checking in my app.
I have to check for various errors in JSON, and in some cases I need to check for a missing primary key in a child relation of type one-to-many.

Here is an example of my json:
```json
  {

    "id": "4",

    "completed": false,

    "createdAt": "2014-09-13T10:00:00+00:00",

    "updatedAt": "2014-09-13T10:00:00+00:00",

    "fields": [

      {

        /* missing id, which is primary key*/

        "name": "good_appointment",

        "type": "radiobutton"

        }

  }
```

This causes a crash in line 55 of DataFilter.swift:
```swift
changes = changes.filter({ change in
            return !inversedPredicatePrimaryKeys.contains(change[localPrimaryKey] as! NSObject)
        })
```

Wouldn't it be nice to handle this error and pass it to the caller of the Sync.changes instead of make the app crash?

**Comment by 3lvis** [comment]
Hi @allemattio,

Making the sync process to fail and pass an error was something quite challenging, that's most likely why it wasn't done like that before.

**Comment by 3lvis** [comment]
Was able to verify here that this isn't an issue anymore: https://github.com/3lvis/Sync/pull/434
