### ISSUE TITLE
Can we have AutoIncrement id as PrimaryKey?

### ISSUE THREAD

**Issue by aamir-nazir** [3lvis/Sync#414]
I need to Sync following JSON. For some reason Rest API not appending actual database **id** in response( id is primary key of Product Model).

```
{
    "products": [{
            "active": true,
            "name": "Product A",
       },
       {
            "active": true,
            "name": "Product B",
       }
    ]
}
```

**Comment by dersvenhesse** [comment]
I suppose an auto increment will not suit your case either. 

The second time your JSON will be inserted with the IDs `3` and `4`. So the exisiting `products` in CoreDate won't be an updated when auto incrementing. Meaning you'll need a way to recognize existing entries, e.g. by name. But that will be basically the same as using `name` as ID in Sync.

Alternatively you should update your API to deliver IDs as well.

**Comment by 3lvis** [comment]
I can concur with what @dersvenhesse. Having a primary key is a key part of how Sync works, this primary key doesn't have to be an integer, it can be anything that can be used to differentiate one element from another.

**Comment by 3lvis** [comment]
@aamir-nazir Closing this for now, let me know if you have any questions.
