### ISSUE TITLE
Export relationships by id

### ISSUE THREAD

**Issue by busu90** [3lvis/Sync#415]
Is there a way to export a objects relationship by id. So if i have a City object that refrences a Country object by a many to one relationship i can get a json like:
{
   cityId: 1,
   cityName: "name",
   countryId: 1
}
I don't want a full nested object.

**Comment by 3lvis** [comment]
@busu90 Hi! Sync doesn't have a way to do that, you would have to get the full nested object and get the one that you need.

**Comment by 3lvis** [comment]
Closing until I hear back from @busu90.
