### ISSUE TITLE
Sync shouldn't delete objects when there's a many-to-many relationship

### ISSUE THREAD

**Issue by batjo** [3lvis/Sync#417]
Consider the following json:

```
[
  {
    "id" : 3,
    "tags" : [
      {
        "id" : 10
      }
    ]
  },
  {
    "id" : 2,
    "tags" : []
  }
]
```

The second object has no tags, and therefore an empty array is send by the server. However as soon as the second object is stored in CoreData it also removes the tag with id 10. Forcing the first object to lose his tag

**Comment by 3lvis** [comment]
Fixed in https://github.com/3lvis/Sync/pull/418
