### ISSUE TITLE
Sync ignores data which has a null value isPrimaryKey

### ISSUE THREAD

**Issue by mrDyos** [3lvis/Sync#419]
File: DataFilter.swift
```swift
let remotePrimaryKeys = changes.map { $0[remotePrimaryKey] }
let remotePrimaryKeysWithoutNils = (remotePrimaryKeys.filter { (($0 as? NSObject) != NSNull()) && ($0 != nil) } as! [NSObject?]) as! [NSObject]
```
First line contains the values of primaryKey from the data.
Second line contains not-empty values of primaryKey from the data.
IMHO If remotePrimaryKeys.count not equals remotePrimaryKeysWithoutNils.count need generate exception.

**Comment by 3lvis** [comment]
@mrDyos This is expected behavior sync we've got reports that having null ids would create an exception. So we went for just discarding objects with NSNull ids.

**Comment by mrDyos** [comment]
```swift
let remotePrimaryKeys = changes.map { $0[remotePrimaryKey] }
let remotePrimaryKeysWithoutNils = (remotePrimaryKeys.filter { (($0 as? NSObject) != NSNull()) && ($0 != nil) } as! [NSObject?]) as! [NSObject]

var remotePrimaryKeysAndChanges = [NSObject: [String: Any]]()
for (primaryKey, change) in zip(remotePrimaryKeysWithoutNils, changes) {
    remotePrimaryKeysAndChanges[primaryKey] = change
}
```

You combine a filtered list of **remotePrimaryKeysWithoutNils** and not a filtered list of **changes**. At the output, it may turn out that **primaryKey** does not match the **change**.
[example](http://swift.sandbox.bluemix.net/#/repl/59bb2dd9580e611f70b04e34)

**Comment by 3lvis** [comment]
Interesting, I'll give it a try :)

**Comment by 3lvis** [comment]
I wasn't able to see the difference... hopefully we can get back this on track if @mrDyos is still looking for this change. Sorry for taking long in replying.
