### ISSUE TITLE
After changing attribute in Model - fetching throws no results from dataStack

### ISSUE THREAD

**Issue by celiagomezdev** [3lvis/Sync#420]
Hi there,

First of all thanks for this pod, it has been very useful so far. 

I'm having now a big problem that I don't know how to solve, but I'm not really sure if it's problem of Sync or is something I'm missing from Core Data itself (as I'm a newbie in all this).

I've been using dataStack context as you explained in the FAQ. Everything working perfectly, I've saved many entries to my model, first from a JSON file and then using some methods to get additional data from an API. Everything successfully. At some point, I wanted to try something and I changed an attribute from Binary Data to Transformable, I've had some errors so I came back to a previous version, but now If I try to load the data again, it doesn't return any result, like if the dataStack would be empty or damaged.

How can I recover all that data? I'm every scared that I might lost all the data forever and I have to start from the beginning :(

That was the method that worked before and now returns an empty array.

```
let dataStack = DataStack(modelName: "UsersModel")
var managedObjectContext: NSManagedObjectContext!
var users = [User]()

func loadData() {
        
        managedObjectContext = dataStack.viewContext
        
        request.returnsObjectsAsFaults = false
        
        do {

            users = try managedObjectContext.fetch(request) as! [User]
           
            for result in users {
                if let databaseName = result.name {
                    if result.name == nil {
                        print("Name is empty for this entry")
                    } else {
                        print("Name: \(databaseName)")
                    }
                } else {
                    print("Could not find attribute name in our model")
                } 
        } catch {
            print("Could not load data from database: \(error.localizedDescription)")
        }
    }
```

**Comment by 3lvis** [comment]
Hi @celiagomezdev 👋 

I'm sorry but once you change the model schema and run the app the cached data will be wiped out and you need to download it again. The reason DataStack does this is that it assumes that the source of truth lives in your backend and instead of having corrupted data it removes everything and expects to download everything from scratch.

**Comment by celiagomezdev** [comment]
Oh ok, that means I've lost all the data. I will start again then :( Thank you very much for answering that fast.

Should then never change any attribute after imported the data. How can I secure the data somehow to prevent this in the future?

The initial problem is that I wanted to map one of the attributes set as 'Binary Data' as an [String]. I've tried this but I didn't managed (I don't know if I should create another issue for this): 

```
let photos = NSKeyedUnarchiver.unarchiveObjectWithData(users.photos) as? [String]
// ==> "football", "soccer", "code"
```
I understand (but probably I'm wrong) that this is implemented once you load your data in your project, so you can access to that property and convert it as [String]. 

But, how I manage to save attribute "photos" as [String] into my model? To be able to import there the data from a web request? For example I implemented this method but it threw an error as it was reading it as Binary Data (and all the problems began when I changed it to Transformable :( ) :

```
//... previous code for the web request...

if let result = results?["result"] as? [String:Any] {
    if let photos = result["photos"] as? [[String:Any]] {
        //This method returns an array of strings: [String]
         let photoURLArray = self.getPhotoURLArray(photos)
         modelResult.setValue(photoURLArray, forKey: "photos")
   }
}
```

**Comment by celiagomezdev** [comment]
@3lvis thanks a lot for your fast reply, I understand now! I'm still figuring out how databases and core data works. I was not doing it properly from the beginning.

**Comment by 3lvis** [comment]
You're welcome :) Just send me a DM on Twitter if I can help in anything else. https://twitter.com/3lvis
