### ISSUE TITLE
Sync object with insert/update/delete, but do not destroy existing relations

### ISSUE THREAD

**Issue by alijaza** [3lvis/Sync#422]
Hello, is there a way to insert/update/delete an object but ONLY update it's related entities? For example, a Conversation entity may have a to-many relationship with Messages. In this case, if you fetch a Conversation object from the server you may only want to get the last message even though other messages may exist and be cached already. If I try to Sync this Conversation, will the messages that are already cached be disconnected from the Conversation? Is there any way to avoid destroying the existing Message relations using a Predicate?

```
{
    "id" : 1,
    "name" : "Jason Alexander",
    "messages" : {
        { 
            "id" : 20,
            "text" : "Hello"
        }
    }
}
```

Thanks in advance!

**Comment by alijaza** [comment]
@3lvis would you mind commenting on this when you have a minute? Thank you!

**Comment by 3lvis** [comment]
Hi @alijaza! I think we've got a similar request before. We don't have support for it out of the box. I think using predicates for this could be possible. 🤔

**Comment by 3lvis** [comment]
I'll think about this and get back to you :)

**Comment by 3lvis** [comment]
Hi, I don't think this would be possible with predicates, using predicates we could avoid doing any changes to related entities but if you want to update them then I think we will have to add a new OperationOption https://github.com/3lvis/Sync/blob/master/Source/Sync/Sync.swift#L19-L30.

**Comment by iballistic** [comment]
Hi,

I have a similar issue but do not use predicates. I have changed my schema and made sure all entities have a primary key - not sure if it is related.

For some reason,  existing relations are broken after importing new data. My use case is that I backup data on one device and restore it to another device which has existing records. 

Could you please let me know if I am missing anything? This should be pretty easy to reproduce. I am running version 3.3.1

**Comment by 3lvis** [comment]
@iballistic I'm afraid this might not be related, Sync uses CoreData's lightweight importing when you change your schema, if it's not possible to auto-migrate the data, it wipes out the entire dataset, CoreData's out-of-the-box solution here is to crash your app. Might be useful to verify that this is indeed a failure in the migration. If you come to this point then it was a failure in migration.

https://github.com/3lvis/Sync/blob/master/Source/DataStack/DataStack.swift#L431

**Comment by iballistic** [comment]
thank you @3lvis

I am sorry confusion, the schema changes were done prior to any export/import process. That is just to make sure I have primary keys for all my entities. 
As far as I can tell my schema is 100% the same across the board, in my case data is not wiped out, just foreign keys are set to null where ever relation exists.

**Comment by 3lvis** [comment]
@iballistic Could you please make a new issue with the JSON and a picture of your schema? Thanks :)

**Comment by iballistic** [comment]
will do,  thank you very much! I will try to create a small app and reproduce in smaller scale and share.

**Comment by 3lvis** [comment]
Work in progress branch to solve this: https://github.com/3lvis/Sync/pull/433. Gonna include a unit test so it's easier to contribute into completing this. Let me know if that's something you're interested in @alijaza :)

**Comment by 3lvis** [comment]
Did a first go at this, should be working for `one-to-many` now.

**Comment by zanderxyz** [comment]
Hi,

I'm having a very similar problem. I have a model similar to the following:

Entities:
Group has one-to-many relationship with Plan
Plan has one-to-many relationship with Participant
Participant has many-to-one relationship with User

Example JSON
{
  "id": 1,
  "name": "Group 1",
  "plans": [
    {
      "id": 1,
      "name": "Plan 1",
      "participants": [
        {
          "id": 1,
          "name": "Participant 1",
          "user": {
            "id": 2,
            "name": "User 2"
          }
        },
        {
          "id": 2,
          "name": "Participant 2",
          "user": {
            "id": 1,
            "name": "User 1"
          }
        }
      ]
    },
    {
      "id": 2,
      "name": "Plan 2",
      "participants": [
        {
          "id": 3,
          "name": "Participant 3",
          "user": {
            "id": 1,
            "name": "User 1"
          }
        },
        {
          "id": 4,
          "name": "Participant 4",
          "user": {
            "id": 2,
            "name": "User 2"
          }
        }
      ]
    }
  ]
}

The first time I sync this it works fine, but if I want to, for example, change the name of a Participant I want to just sync the following JSON as a Participant and not lose any existing relationships:

{
  "id": 1,
  "name": "New name"
}

Is this what your pull request above is meant to solve with the new operations?

Thanks

**Comment by batjo** [comment]
Both issues should be fixed in the master branch. If you still have problems syncing json, please reopen at if possible add a failing test case. Thanks!
