### ISSUE TITLE
Paging of records override existing records

### ISSUE THREAD

**Issue by sagargondaliya** [3lvis/Sync#427]
We have around more then 3000 records, so we are fetching it by paging of 100 records per page and syncing it in database, but when we fetch another 100 records and sync it, then rather then adding it to table , it override the records. 

Here is my code, can we missing something ?

`func syncProduct(){
        self.productDataSynced = false
        
        //Updated sync date time
        var parameters: Parameters = [:]
        if let date = Defaults[.productSyncTime] {
            parameters[AppConstants.RequestKey.updatedDate] = date
        }
        
        NetworkClient.sharedInstance.request(AppConstants.serverURL, command: AppConstants.URL.ProductSync, method: .post, parameters: parameters, headers: ApplicationData.sharedInstance.authorizationHeaders, success: { (response, error) in
            
            //save product sync date time
            let responseData = response as? [String : Any] ?? [:]
            Defaults[.productSyncTime] = responseData[AppConstants.ResponseKey.serverLastSync] as? String
            
            // main list
            if let list = responseData[AppConstants.ResponseKey.list] as? [String: Any] {
                if let productList = list[AppConstants.ResponseKey.list] as? [[String : Any]] {
                    
                    Sync.changes(productList, inEntityNamed: AppConstants.Entity.Product, dataStack: self.dataStack!, completion: { (error) in
                        
                        if let err = error {
                            print("error in product sync: \(err.localizedDescription)")
                        }
                       
                    })
                }
            }
        }) { (failureMessage) in
            print(failureMessage)
        }
    }`

**Comment by 3lvis** [comment]
Hi @sagargondaliya,

This has been mentioned before, when Sync gets new data it will try to diff the data that is getting with the local data, and removes the local elements that aren't found in your JSON, it does this because Sync tries to match what you have on your servers. If you want to stop this behaviour you need to use a predicate, a predicate basically tells Sync: "Hey,  locally only Sync the elements that conform to this predicate", so if you want to avoid local elements you could make a query where you get all the ids and tell Sync to avoid any element with those ids.

**Comment by 3lvis** [comment]
I believe using operations could solve your issue as well, of course assuming you don't want to remove records and do the removing part in a separate process.

```swift
// This only inserts and updates, no deletions.
dataStack.sync(usersB, inEntityNamed: "EntityUser", operations: [.insert, .update], completion: nil)
```

I hope this helps, otherwise let me know and we'll figure it out.
