### ISSUE TITLE
Syncing abstract entieties

### ISSUE THREAD

**Issue by MichalAlgor** [3lvis/Sync#428]
Hi!
I have problem when syncing abstract entities.
My model looks similar to the 239 model from tests:
<img width="568" alt="zrzut ekranu 2017-10-11 o 13 35 50" src="https://user-images.githubusercontent.com/14600264/31439499-a5f216e6-ae8c-11e7-8360-9d9b8bb77f42.png">
But in my application I need to operate on passengers. So when I have this JSON:

	 {
		 "id": 7,
		 "name": "Kimi Raikkonen",
		 "car":{
			 "id": 31,
			 "max_speed": 370,
		 }
	 }

It is not recognizing the Car (id: 31) as a Racecar (there is maxSpeed attribute). 
Is there a way to fix that?

**Comment by 3lvis** [comment]
Hi @MichalAlgor,

Does it work if you name your relationship `racecar` instead of `car`?



	 {
		 "id": 7,
		 "name": "Kimi Raikkonen",
		 "racecar":{
			 "id": 31,
			 "max_speed": 370,
		 }
	 }

**Comment by MichalAlgor** [comment]
Probably, but my database is allready structured that way. Also halving it this way makes it easy to use in my usecases.

**Comment by 3lvis** [comment]
Thanks for getting back to me. I'm not sure how we could make it work given the constraints. My only suggestion is that you perform some JSON pre-processing so it changes the key before calling Sync. If you have any other ideas let me know :).

**Comment by 3lvis** [comment]
Closing for now, waiting to hear back from @MichalAlgor.
