### ISSUE TITLE
insert records with predicate of User.DeptId != User.EmpId

### ISSUE THREAD

**Issue by mailforkumar** [3lvis/Sync#429]
Have an use case similar to replace all records with new JSON array where DeptId==EmpID, but did not see that working.

let **predicate**= NSPredicate(format: "DeptId != EmpId")                
Sync.changes(json, inEntityNamed: "User", predicate: **predicate**, parent: nil, inContext: backgroundContext, completion: { error in
                   ...
                    completion(error)
                  ....
                })

But 
let request = NSBatchDeleteRequest(fetchRequest: fetch)
self.dataStack.mainContext.execute(request)
then sync with new JSON works

Note : Predicate like DeptId=1238 kind works perfect.

**Comment by 3lvis** [comment]
Hi @mailforkumar,

Not sure if this is a Sync related issue or a Core Data specific one. To see if I understood correctly. After filling your User with elements you want to replace all the elements where `DeptId` (a field in your model) are different from `EmpId` another field in your model? Maybe having an example of your JSON file and Core Data model could also help to give even more information.

Thanks!

**Comment by 3lvis** [comment]
Closing for now for lack of response, will reopen once we get more info.
