### ISSUE TITLE
Sync.changes breaks relation in the existing records. 

### ISSUE THREAD

**Issue by iballistic** [3lvis/Sync#431]
Sync.changes(json, inEntityNamed: "EntityUser", inContext: appDelegate.persistentContainer.viewContext)  breaks relation in existing records. Test 3 was created before the import. I am running version Sync-3.3.1. I can provide a sample project if it is required. 

![dbview](https://user-images.githubusercontent.com/33011532/31924286-5de2ae46-b83d-11e7-9e2b-12cd9a2cee96.png)
![schema](https://user-images.githubusercontent.com/33011532/31924287-5e2bc504-b83d-11e7-9b26-540bfc85cf2c.png)

[Import.json.zip](https://github.com/3lvis/Sync/files/1409480/Import.json.zip)

**Comment by iballistic** [comment]
Code is used to import: 
            let from : URL = appDelegate.applicationDocumentsDirectory.appendingPathComponent("Import.json")
            let data = try! Data(contentsOf: URL(fileURLWithPath:  from.path))
            let json = try! JSONSerialization.jsonObject(with: data, options: []) as! [[String: Any]]
            Sync.changes(json, inEntityNamed: "EntityUser", inContext: appDelegate.persistentContainer.viewContext) { error in

**Comment by 3lvis** [comment]
Hi! I wasn't able to reproduce the issue, could you check the code?

https://github.com/3lvis/Sync/pull/432

**Comment by iballistic** [comment]
Yes, I will be happy to check whatever is required. I presume I need to check out #432 and modify and commit? Sorry I have not done this before...

Regardless I can tell what you are doing differently. This must be a two-step process. Either create a record before importing or use two new files that I am attaching. First import1. json, and then import2.json, after you import import2.json all relations in import1 will be broken. 
[Archive.zip](https://github.com/3lvis/Sync/files/1413088/Archive.zip)

**Comment by 3lvis** [comment]
Thanks for the extra info. I’ll have a look. :)

**Comment by pgawlowski** [comment]
Same issue :( Any news?

**Comment by 3lvis** [comment]
Hi pulled your changes into https://github.com/3lvis/Sync/pull/432. 

I think there is a misunderstanding and Sync is doing what it's supposed to. In your second JSON none of the first elements is present, meaning Sync believes it was removed from the database. If you want Sync to assume that the new elements are just meant to be inserted or updated and not deleted you can do the following:

```swift
dataStack.sync(usersB, inEntityNamed: "EntityUser", operations: [.insert, .update], completion: nil)
```

I updated the test to show what this does.

**Comment by iballistic** [comment]
oh great! thank you very much! It makes sense
