### ISSUE TITLE
Xcode 9 and iOS 11 problem

### ISSUE THREAD

**Issue by dneykov** [3lvis/Sync#436]
Hi,
I'm using this awesome library for a while but after updating to Xcode 9 I have following message in the console when inserting/updating/deleting:

```
CoreData: error: Error opening store: Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory" UserInfo={NSFilePath=/path/to/file.sqlite}
CoreData: error: (6922) I/O error for database at /path/to/file.sqlite.  SQLite error code:6922, 'disk I/O error'
CoreData: error: exception handling request: <NSSQLFetchRequestContext: 0x1c019da80> , I/O error for database at /path/to/file.sqlite.  SQLite error code:6922, 'disk I/O error' with userInfo of {
    NSFilePath = "/path/to/file.sqlite";
    NSSQLiteErrorDomain = 6922;
}
CoreData: error: -executeRequest: encountered exception = I/O error for database at /path/to/file.sqlite.  SQLite error code:6922, 'disk I/O error' with userInfo = {
    NSFilePath = "/path/to/file.sqlite";
    NSSQLiteErrorDomain = 6922;
}
```

And everything is working as expected. Anyone can explain what are these messages for?
Thanks.

**Comment by 3lvis** [comment]
Hi! Found the same problem here:

https://github.com/magicalpanda/MagicalRecord/issues/461

Can you try upgrading to the latest version of Sync and wiping derived data and simulator data?

I think the problem is related to dropping the database, we rolled back the method that we were using on Sync 3.3.1, so I hope you don't get the same warning again.

**Comment by dneykov** [comment]
Hi,

I was using 4.0.1 and just updated to 4.0.2 `Installing Sync 4.0.2 (was 4.0.1)` and delete derived data but warnings still appears. I'm using real device for testing.

Thanks.

**Comment by 3lvis** [comment]
Hi @dneykov,

Sadly, I'm not able to reproduce your issue. 😕

**Comment by dneykov** [comment]
Any suggestions where to look about the warnings?

**Comment by 3lvis** [comment]
I'm not sure how I would be able to help here, this seems like a Core Data related issue more than anything.

**Comment by petkrein** [comment]
Hi @3lvis,

have the same warnings when dropping first and updating.

**Comment by 3lvis** [comment]
I wonder what the problem is, I haven't been able to reproduce this myself
