### ISSUE TITLE
Help Wanted – Datastack.sync JSON Array of Dictionaries

### ISSUE THREAD

**Issue by windexb** [3lvis/Sync#440]
I’m having a problem even doing a basic sync with this library.  I’ve looked through issues and sample code and still no luck.  What’s even more interesting is that I no longer can fetch my user data from core data after I assumed I botched the sync. 

Goal: I’m trying to simply update one user after a fetch data from the server. What I think I’m struggling with is the sync parameter changes: [[String: Any]] – Array of Dictionaries and the returned JSON object from Alamofire. Especially with converting from JSON Data. In the sample code there’s a lot of forced typing and I’m not sure why. I tried force typing too and it still didn’t work. So my last attempt is the following. 

JSON User Record returned by the server: - print(result) in swift

`
{
"_v" = 0;
“_id" = 59fbdcf46df9cac384a605f1;
"client_id" = "9A4727D4-2206-41B4-9B6E-6B4C73B3C14C";
email = "john.smith@gmail.com";
}
`

CoreDataMap is the following 
Core Data Model  has “clientId” sync.isPrimaryKey true
`clientId String`
`email String`

            Alamofire.request(dataRequest).responseJSON { (response) in
                if let responseValue = response.result.value {

                    var arrayDictionary : [[String: Any]] = []
                    let oneElement = ["data": responseValue ]
                    arrayDictionary.append(oneElement)

                    self.dataStack.sync(arrayDictionary, inEntityNamed: "User", completion: { (error) in
                        if let error = error {
                            print(error)
                        } else {
                            
                        }
                        
                    })
                    
                    
                }
                }

There may be multiple issues going on but any insight would be helpful!

**Comment by 3lvis** [comment]
There you go, I hope it helps!

https://github.com/3lvis/Sync/pull/441

Basically two changes were required to the Core Data model.

- clientID 
Needs `sync.isPrimaryKey` equal to `yes`

- id
Needs `sync.remoteKey` equal to `_id`
