### ISSUE TITLE
true in JSON is still ignored

### ISSUE THREAD

**Issue by max-pfeiffer** [3lvis/Sync#449]
I just had the same issue:  https://github.com/3lvis/Sync/issues/399
Using the latest V4.0.3.

I was banging my head at the wall for an hour since I found out that the JSON processing in the sync library is the problem.

When I have true values in my JSON this is not set correctly on Boolean propertis in core data objects.

I will try and provide a pull request with a test to reproduce that issue, but don't count on that, too much work right now.

**Comment by max-pfeiffer** [comment]
@3lvis : made a pull request with a test: https://github.com/3lvis/Sync/pull/452

**Comment by 3lvis** [comment]
Modified the query and seems to be working. I wonder what was the issue. https://github.com/3lvis/Sync/pull/455/commits/5c93bf01082aace2a1cf0c79ad4e97276eb9e9d3

**Comment by 3lvis** [comment]
Closing for now until we get more feedback.
