### ISSUE TITLE
Is there way to set the remotePrimaryKey for camelCase?

### ISSUE THREAD

**Issue by shiangyichen** [3lvis/Sync#456]
I set hyper.isPrimaryKey for my attribute "productId", but it save nothing to database, then i trace the code, find that remotePrimaryKey is "product_id" not "productId"

In NSEntityDescription+PrimaryKey.h - sync_remotePrimaryKey
it seems that default format is hyp_snakeCase, Is there way to set the remotePrimaryKey for camelCase? 
Thanks so much!

**Comment by 3lvis** [comment]
Hi! You can set both. `sync.isPrimaryKey` and `sync.remoteKey`

**Comment by shiangyichen** [comment]
@3lvis  Thank you for your response. But i set the remoteKey & isPrimaryKey, it seems sync_remotePrimaryKey() would translate to snackcase automatically, it will cause nil result...
If i change the sync_remotePrimaryKey() in file NSEntityDescription+PrimaryKey.m to [primaryKeyAttribute.name hyp_camelCase], it work fine. So is there a method or option  like inflectionType for remotePrimaryKey  to camelCase for use? Thank you.

**Comment by 3lvis** [comment]
I think I see what’s going on now. Could you share with me your JSON and Core Data model, please?

**Comment by 3lvis** [comment]
Closing for now, will reopen once we get more information.
