### ISSUE TITLE
I have a two relationships... object-->object-->object

### ISSUE THREAD

**Issue by jimijon** [3lvis/Sync#457]
Ok, how I am supposed to do this (it worked in the 2x version)

I have 25K Products which have a relationship to Subcategory which has a relationship to Category.

I don't want my JSON to have all that in one call.

So I first sync subcategories with related to one category. This works.
Next I sync product with just a relationship to Subcategory. This then nils out the relationship from from product.subcategory.category. Category is nil.

However, if I go to subcategory, the relationship to Category is intact!!

How am I supposed to sync this? Now remember this was never a problem in the older version.

**Comment by 3lvis** [comment]
Hi James,

I think I understand what you mean, having an example of your JSON and Core Data model would help me a lot.

This is what I understood so far.

## Step 1: Add category with ID 1
```swift
let category = //... new category with ID 1
try! dataStack.mainContext.save()
```

## Step 2: Sync subcategories of category with ID 1
```json
[
  {
    "id": 100,
    "category_id": 1
  },
  {
    "id": 101,
    "category_id": 1
  },
]
```

```swift
dataStack.sync(json, inEntityNamed: "Subcategory", parent: category1....
```

## Step 3: Sync product with subcategory
```json
[
  {
    "id": 900,
    "subcategory": {
      "id": 100
    }
  }
]
```

```swift
dataStack.sync(json, inEntityNamed: "Product"...
```

Then if you do, product.subcategory.category it gives nil instead of giving the category with the ID 1.

Is this correct?

**Comment by jimijon** [comment]
It’s pretty big…. but yes, you have it correct here as you described.

**Comment by jimijon** [comment]
Any news?

**Comment by 3lvis** [comment]
Hi @jimijon,

Haven't had the chance to look into it yet but would be helpful to get a unit test that reflects the issue.

**Comment by jimijon** [comment]
I created the unit test in my fork. Really would like to get this working again.

**Comment by 3lvis** [comment]
Hi @jimijon,

I can't seem to find it, could you share the link?

https://github.com/jimijon/Sync/branches/all

**Comment by jimijon** [comment]
D’oh, forgot to push.

Should be there now with a pull request.

**Comment by jimijon** [comment]
Any news on this?

**Comment by batjo** [comment]
Hi @jimijon, I was having the same issue and was able to fix it. Please check my changes: https://github.com/3lvis/Sync/commit/112520071007f83c8af48328fc477d705f97cdc4 and let me know if that fixed your issue as well
