### ISSUE TITLE
How can we map nested json key?

### ISSUE THREAD

**Issue by aamir-nazir** [3lvis/Sync#460]

**Comment by 3lvis** [comment]
## Deep mapping

```json
{
  "id": 1,
  "name": "John Monad",
  "company": {
    "name": "IKEA"
  }
}
```

In this example, if you want to avoid creating a Core Data entity for the company, you could map straight to the company's name. By adding this to the *User Info* of your `companyName` field:

```
sync.remoteKey = company.name
```


https://github.com/3lvis/Sync/blob/d8e7f24664e82b166585206fcf84919b0f0eb171/docs/PropertyMapper.md#deep-mapping

**Comment by aamir-nazir** [comment]
Yeah I expecting same format but didn't tried, Thank you for very quick response.

**Comment by 3lvis** [comment]
I hope it works out, otherwise I'll reopen this issue :)
