### ISSUE TITLE
Saving Json data in Two entities having relation Fails on alternate "fetching and storing" Help!

### ISSUE THREAD

**Issue by aalikhokhar** [3lvis/Sync#461]
Hello, 
I am storing json data into two entities as FormInfo and FormQuestions having relation. I am fetching json data from server at every  login and store into given entities. Sync store it perfectly first time and if I logout from app and while login fetching json again same function called to store data but it fails to store without any error or crash. Even I have checked Sqlite file. Thanks 
Below is my json : 
`{
	"dca_forms": [{
		"form_id": "1",
		"form_name": "Form 1",
		"type": "dca",
		"form_quesions": [{
				"ques_id": "1",
				"heading": "heading a",
				"question": "questin one?"
			},
			{
				"ques_id": "2",
				"heading": "Heading 2",
				"question": "Question 2?"
			}
		]
	}],
	"pi_forms": [{
		"form_id": "2",
		"form_name": "Form 2",
		"type": "pi",
		"form_quesions": [{
				"ques_id": "1",
				"heading": "heading a",
				"question": "questin one?"
			},
			{
				"ques_id": "2",
				"heading": "Heading 2",
				"question": "Question 2?"
			}
		]
	}]
}`
Here is swift implementation: 
`let dcaformsJson = formsJson["dca_forms"] as! [[String: Any]]
                            self.storeData(json: dcaformsJson, entityName: "FormsInfo")
                            
                            let piformsJson = formsJson["pi_forms"] as! [[String: Any]]
                            self.storeData(json: piformsJson, entityName: "FormsInfo")
func storeData(json: [[String: Any]], entityName: String) -> Void {
        Sync.changes(json, inEntityNamed: entityName, dataStack: self.dataStack) { errorDB in
            if errorDB == nil{
                debugPrint("Saved")
            }else{
                debugPrint("db error: %@", errorDB!.localizedDescription)
            }
            
        }
    }`

**Comment by 3lvis** [comment]
Hi @aalikhokhar,

I'm not sure what could be failing, would it be possible to get a unit test or a sample project reproducing the error? Would be of great help. Thanks in advance.

**Comment by aalikhokhar** [comment]
Issue fixed if I delete both entities records when logging out. And when loging in again Sync Inserts Fine.

**Comment by 3lvis** [comment]
I see :), closing this then.
