### ISSUE TITLE
App crashed when try to sync invalid object

### ISSUE THREAD

**Issue by krasnodar95** [3lvis/Sync#462]
The Entity has not optional relation. From the server comes json where this field is == null(i.e. not valid). When you try to synchronize, the application crashes(Moreover xcode crashes, but this is hardly a library problem).

**Comment by batjo** [comment]
Any Swift code will crash when you assign a nil value to a non-optional so I don't think this is related to Sync. You could change your model to be an optional or you can do some JSON preprocessing and throw an exception when invalid data is coming from the server.
