### ISSUE TITLE
Update associated entity's object.

### ISSUE THREAD

**Issue by aamir-nazir** [3lvis/Sync#463]
I need to update `Product id: 5` thats associated to User object, but I need to keep all existing associated Products. I tried using `operations: [.insert, .update]`. This destroys all existing associations.

```
{
  "id": 1,
  "name": "User 1",
  "products": [
    {
      "id": 5,
      "name": "Updated Product"
   }]
}
```

**Comment by aamir-nazir** [comment]
@3lvis do you mind commenting on this?

**Comment by 3lvis** [comment]
Hi @aamir-nazir,

Sadly at the moment the .insert, .update will only work for the users, the products will do all three operations: insert, update and delete. I saw your comment on #433, I think that would solve your problem but I haven't had time to wrap it up.

**Comment by 3lvis** [comment]
Could you try that branch and see if it fixes your issue?

**Comment by batjo** [comment]
This has been merged in the master branch now. If you still have problems please reopen.
