### ISSUE TITLE
How to ignore local data so it's not deleted when sync

### ISSUE THREAD

**Issue by dneykov** [3lvis/Sync#464]
Hi guys,

Happy New Year.

I have a project where I use Sync to synchronize with my server. Downloading data from the server and editing this data and send it back to the server. I have the option to edit data on the devices and I'm using flag `offline` to indicate if there is locally changed data to avoid override from the server. This works great using predicate `predicate: NSPredicate(format: "offline == %@", NSNumber(value: false))`

But now I have another flag `locallyCreated` which is used for items created locally on device and they only stays on the device which are created. And here my problem comes because these local items are removed when the sync runs because they are not in the json from the server. I'm trying to use predicate but to working `predicate: NSPredicate(format: "offline == %@ OR locallyCreated == %@", NSNumber(value: false), NSNumber(value: false))`

Any suggestions?
Thanks.

**Comment by dneykov** [comment]
Sorry for opening this issue is totally logical error, nothing related to the library.

**Comment by 3lvis** [comment]
Nice to hear that you got this fixed, Daniel. Happy new year!
