### ISSUE TITLE
is there a way to export an object with relations with a constraint ?

### ISSUE THREAD

**Issue by siempay** [3lvis/Sync#474]
consider a  `User: { ... , comments: <relation>}`
is there a way to do something like export a `User` with comments that satisfy a condition?
i.e :
 `let user = User(); user.export(){ user in 
   some condition 
}`

**Comment by 3lvis** [comment]
Hi @siempay,

We don't have support for that or have considered until now.

**Comment by siempay** [comment]
one more question: 
about this `If you want to use id for the remote primary key you also have to add the flag sync.remoteKey and write id as the value.`
I did not understand it! 
what I wanna do is to create a primary key (i.e localKey), and keep the attribute `id` as a remote key that want to update when I sync an object 
example : 
T1 : `user = User() // { id: 0, localKey:1, ....}`
T2 : `user.sync()`
T3: get object user form the server and do `insertOrUpdate` 
T4:  `user =  // { id: 77, localKey:1, ....}`
 
what I think is that I am gonna add an attribute `localKey` to my model and mark it as `sync.isPrimaryKey` , and keep the attribute `id` as is (no flag added ) 
am I right?

**Comment by 3lvis** [comment]
Hi @siempay,

As I understand, in your JSON you have `id` and in Core Data you have `customID`?

Or could you help me understand what's your JSON primary key and your Core Data primary key?

**Comment by siempay** [comment]
primary key of core data is `customID` and for the json is id, that is why I was think of sending this `customID` with the json, and then make the server return it back.
so I would send and object `user = {id:0, customID:2,....}` and then the server will store the object user and return it back as `user = { id:1, cosutomID:2, ....}`, I dont know what are the best practices

**Comment by 3lvis** [comment]
Does this work?

Core Data:
customID (sync.isPrimaryKey: YES) (sync.remoteKey: id)

**Comment by siempay** [comment]
I am the one who asked the question hhhh, but it worked, setting the `customID` to (sync.isPrimaryKey: YES), and keeping the `id` as is, (not adding any `(sync.remoteKey: id)`) .

**Comment by 3lvis** [comment]
Perfect! Let me know if I can help with anything else :)
