### ISSUE TITLE
Missing required module 'Sync.NSEntityDescription_PrimaryKey'

### ISSUE THREAD

**Issue by kaszap82** [3lvis/Sync#475]
Hi!

Could you help me please, I get this error at the import Sync line in my project. I used Sync 2 years ago, and now I tried to convert my project the swift3. I use the latest version of sync.

**Comment by 3lvis** [comment]
Hi @kaszap82,

Could you try adding

`import Sync` in the top of your project?

**Comment by kaszap82** [comment]
At the top of a swift file? (same issue) Or how do you mean "top of the project"?

**Comment by 3lvis** [comment]
what about

`import Sync.NSEntityDescription_PrimaryKey` at the top of the file?

**Comment by kaszap82** [comment]
Not working: No such module 'Sync.NSEntityDescription_PrimaryKey', I check the header search path, and there is the ${PODS_ROOT} recursive, so I think it can be find in this way.

**Comment by kaszap82** [comment]
Sorry, it's an old project, I think there was a project config error, because now it's working. Sorry again, and thanks for your time!

**Comment by 3lvis** [comment]
I'm glad you got it working and sorry for breaking so much of your code!

**Comment by hanumanAbacus** [comment]
I am facing the same issue, when is use `use_frameworks!` in pod file, it compiles without any issue, else it will give the above error

**Comment by 3lvis** [comment]
@hanumanAbacus you should use 'use_frameworks!', it's the norm since iOS7 I believe.

**Comment by basitsaleemmb** [comment]
@3lvis  i am still facing the same issue. i have used  'use_frameworks!', but its not going to work :(
