### ISSUE TITLE
Sync crashes retrieving related data

### ISSUE THREAD

**Issue by achirkof** [3lvis/Sync#476]
Hi @3lvis and @batjo!

I have found that changes made during last 10 days breaks the Sync. I have to rollback my project to commit `6361a7b` which is working well.
I'm prepared a [little app to reproduce a bug](https://github.com/achirkof/Sync_bug_reproduce.git). You can grub it and run to catch the crash.

If you put an Exception breakpoint you'll catch error `Sync_bug_reproduce[12030:871819] -[__NSCFString timeIntervalSinceReferenceDate]: unrecognized selector sent to instance 0x604000443f30` and [line](https://github.com/3lvis/Sync/blob/87cfe00cc93b758431a205991a7044915d2d3169/Source/Sync/NSManagedObjectContext%2BSync.swift#L48) in code where it's thrown.

Crash appears because of `sync.remoteKey` parameter.

<a href="https://cl.ly/pQHp" target="_blank"><img src="https://d2ffutrenqvap3.cloudfront.net/items/0i2l2a2U2m2P2V24370L/%5B201be88eb0c5a74030db15d42d362842%5D_Image%25202018-02-10%2520at%25201.39.00%2520AM.png" style="display: block;height: auto;width: 100%;"/></a>

If I remove this parameter - no crash but related data are not synchronising.

<a href="https://cl.ly/pQsq" target="_blank"><img src="https://d2ffutrenqvap3.cloudfront.net/items/0C060i1f3I0a380q1I0i/%5Bd10c09840e0106c3fc046bc1f096afe9%5D_Image%25202018-02-10%2520at%25201.36.21%2520AM.png" style="display: block;height: auto;width: 100%;"/></a>

Here is data model

<a href="https://cl.ly/pQpM" target="_blank"><img src="https://d2ffutrenqvap3.cloudfront.net/items/3w3U2H1z2T18290g0n3U/Image%202018-02-10%20at%201.53.45%20AM.png" style="display: block;height: auto;width: 100%;"/></a>

**Comment by 3lvis** [comment]
Hi @achirkof,

Thanks for reporting this issue :) Fix incoming

https://github.com/3lvis/Sync/pull/477

**Comment by achirkof** [comment]
Thanks @3lvis !
I’ll check it a little bit later today.

**Comment by achirkof** [comment]
Hi @3lvis !
It's strange, but pointing to `pod 'Sync', '~> 4'` I still have this issue. Only if I pointing directly to commit issue not appear.

**Comment by 3lvis** [comment]
@achirkof The fix is not released yet, need to make a new release :)
