### ISSUE TITLE
Relation ID and nested object in JSON at same time

### ISSUE THREAD

**Issue by JanRajtr** [3lvis/Sync#478]
Hello,

I am currently trying to implement Sync unfortunately I stuck with following scenario. API returns this JSON:
```
[
  {
    "id": 1,
    "name": "New York",
    "weather_id": 1,
    "weather":{
        "id":1,
        "condition":"sunny"
     }
  }
]
```

In this example the Sync ignores the nested object "weather" because , regarding the "weather_id", it does not exist in the time of syncing. This makes sense, however Sync skips also the nested JSON object "weather" in this case. Does exist any solution for this scenario? I am not able to get "weather" object before the main object so I cannot provide it before the sync.

Thank you for your help and Sync library.

J.

**Comment by pgawlowski** [comment]
@JanRajtr 

Hello,
Managed to handle your problem? I've got quite similar issue, however it is not creating any kind of nested relationship, not only the one with same ID's. Maybe you can give a some sort of hint how to move forward.

**Comment by JanRajtr** [comment]
Hello, 
well my workaround at this moment was to implement controllers in API which returns all objects in advance. Anyway I have been thinking about it and in my some of next versions of my app I would be able to remove the attribute with "id" from main object, because I hopefully will not need it anymore. It does not solve the issue but at least works on consistent APIs and I don't need to cache all entities in advance...

**Comment by 3lvis** [comment]
Thanks for your support in this library. It has been a while since I used CoreData in any of my projects and it's hard for me to maintain this library. If you have been part of the Sync contributors group and want to take ownership of the library let me know to elvisnunez@me.com. For now, I'll be archiving this library.
