### ISSUE TITLE
Date formatter issue while mapping with core data

### ISSUE THREAD

**Issue by rajtharan-g** [3lvis/Sync#479]
I'm getting the response JSON from API in the format like given below
"2018-02-13T12:08:54.839216Z"

 But when I fetch the date from core data after saving it and if I print the date in the format as "yyyy-MM-dd'T'HH:mm:ss.SSSSSS'Z'", the I'm getting the value as shown below
"2018-02-13T12:08:54.000000Z"
The value after seconds is not getting mapped correctly. Or is there any way to set the date format from our side in iOS.

**Comment by rajtharan-g** [comment]
@3lvis Any update on this issue please...Help wanted

**Comment by 3lvis** [comment]
Hi @rajtharan-g,

Sadly I haven't got the time for it but check the DateParser class (and tests), so you can add a fix for it. https://github.com/3lvis/Sync/tree/master/Source/DateParser

**Comment by rajtharan-g** [comment]
Im closing the issue as it got solved in the above pull request.
