### ISSUE TITLE
Export with different remote key doesn't respect nested attributes. 

### ISSUE THREAD

**Issue by joeboyscout04** [3lvis/Sync#482]
Great library.  I recently ran into an error with the exporting of JSON and thought I'd share it. 

Considering a simple json:
`{
    "id": 6,
    "name": "Shawn Merrill",
    "contact": {
      "email": "myemail@gmail.com"
    }
  }`

it is possible to flatten out the JSON in the Core data model completely to remove the nesting for "contact.email" property.  This removes an extra attribute and model from CoreData, and keeps things simple. 

`sync.remoteKey = contact.email`

This works fine when extracting from JSON to CoreData.  However, attempting `.export()` of the same model results in:
`{
    "id": 6,
    "name": "Shawn Merrill",
    "contact.email": "myemail@gmail.com"
  }`

where the key with dots is kept together.  So the JSON doesn't export in the same format as it was imported.

**Comment by 3lvis** [comment]
Nice catch, @joeboyscout04!

**Comment by joeboyscout04** [comment]
I think I got it fixed. Let me know how it looks to you.
