### ISSUE TITLE
Trying a lot but the syncing is not working 

### ISSUE THREAD

**Issue by iOSUser110** [3lvis/Sync#483]
reponse from service is there , but sync is not happining ??

**Comment by 3lvis** [comment]
Hi @iOSUser110,

Would you mind sharing an example of your JSON as well as your Core Data model?

**Comment by JupiterJones** [comment]
I've been having a similar issue (on and off) and it's always been a problem with my data model.

Is there a way to get greater visibility - some context about what caused the error?

ps Thanks for the awesome framework. :)

**Comment by 3lvis** [comment]
Sadly, this is all hidden behind Core Data's magic. But you can log what changes are done by Core Data following these steps: https://github.com/3lvis/Sync/blob/master/docs/faq.md#logging-changes

**Comment by 3lvis** [comment]
Closing for now, let me know if this is still an issue.
