### ISSUE TITLE
DataStack and NSBatchUpdateRequest

### ISSUE THREAD

**Issue by max-pfeiffer** [3lvis/Sync#486]
This is just a question to clarify: looking at the DataStack source and comments I learned that you should use a backgroundContext to modify objects. You should not use the main context.

To my understanding this is not true for the batch requests introduced in iOS 8 because these are bypassing the NSManagedObjectContext. Changes are written directly to the persistent store. This is a least what the [official documentation](https://developer.apple.com/library/content/featuredarticles/CoreData_Batch_Guide/Introduction/Introduction.html#//apple_ref/doc/uid/TP40016719-SW1) states or Apple broadcasted in one of their [frenetic videos](https://developer.apple.com/videos/play/wwdc2015/220/).

 So I suppose this code should be allright:

```
self.dataStack.sync(data, inEntityNamed: entityName, predicate: fetchRequest.predicate) { error in
                let batchUpdaterequest = NSBatchUpdateRequest(entityName: entityName)
                if let predicate = fetchRequest.predicate {
                    batchUpdaterequest.predicate = (predicate.copy() as! NSPredicate)
                }
                batchUpdaterequest.propertiesToUpdate = [NSManagedObject.lastModifiedKey : NSDate()]            
                self.dataStack.mainContext.execute(batchUpdaterequest)
        }
```
The alternative would be something like this which seems to me a little silly because changes get written to the same persistent store:
```
self.dataStack.sync(data, inEntityNamed: entityName, predicate: fetchRequest.predicate) { error in
                let batchUpdaterequest = NSBatchUpdateRequest(entityName: entityName)
                if let predicate = fetchRequest.predicate {
                    batchUpdaterequest.predicate = (predicate.copy() as! NSPredicate)
                }
                batchUpdaterequest.propertiesToUpdate = [NSManagedObject.lastModifiedKey : NSDate()]
            
            self.dataStack.performInNewBackgroundContext{ backgroundContext in
                    try backgroundContext.execute(batchUpdaterequest) // context save is omnitted here because it is not needed for a batch request
            }
        }
```

**Comment by 3lvis** [comment]
Thanks for your support in this library. It has been a while since I used CoreData in any of my projects and it's hard for me to maintain this library. If you have been part of the Sync contributors group and want to take ownership of the library let me know to elvisnunez@me.com. For now, I'll be archiving this library.
