### ISSUE TITLE
* What to do when we use Object Inheritance?

### ISSUE THREAD

**Issue by Sydney-o9** [3lvis/Sync#487]
Awesome work with `Sync` - quick question.

With entity inheritance, I have been unsuccessful so far, does Sync support persistance such as:

```
{
    "garage":  {
        id: 1,
        cars: [
            { id: 10, type: "subaru", color: "blue" },
            { id: 11, type: "racecar", turbo: true }
        ]
}
```

With a simple inheritance graph, where `Car` is an abstract parent and `Subaru` and `RaceCar` inherit from the base class

```
Car -----> Subaru
  |
  |-------> RaceCar 
```

 I could not get sync to persist data to the child classes, only fields on the base class are persisted.

Any ideas?

----
I could see working with inheritance with Sync works when persisting from the Child class going upwards [like here](https://github.com/3lvis/Sync/blob/98c6c1f881ad47e216600128edf94363c7ab8718/Tests/Sync/SyncTests.swift#L1129) but I wonder if we can do it from the parent class going downard to the children classes...

**Comment by Sydney-o9** [comment]
Something similar to this basically:

https://github.com/evermeer/EVReflection#what-to-do-when-you-use-object-inheritance

This is not supported yet - is it?

**Comment by 3lvis** [comment]
Hi @Sydney-o9! Good question and sorry for the late reply, I've been on vacations 🏖. I do remember we added some support for inheritance but as you mention it might not cover your case. Could you please make a unit test with a fork to see if I can add a fix for it? Thank you in advance.
