### ISSUE TITLE
export() includes <__NSArrayM 0x1c045d190> on first toMany relationship

### ISSUE THREAD

**Issue by JupiterJones** [3lvis/Sync#488]
I'm exporting an NSManagedObject with a toMany relationship. The first toMany relationship ends up in the string as follows:

```
["title": "first top level object", "nestedRelationship": <__NSArrayM 0x1c045d190>(
{ comment = "first related object";
...etc.
```

However, it only appears on the first toMany export. All other toMany relationships export as expected.

Also, you'll notice that everything other than the top level object exports as key = value, rather than key : value.

I've had a quick look at the Sync source but can't see what's causing this. I'm hoping someone else has seen it and I've just made a silly mistake.

Xcode 9.2
To export I'm using:
```
var exportOptions = ExportOptions()
exportOptions.inflectionType = .camelCase
exportOptions.relationshipType = .array

let exportData = topLevelObject.export(using: exportOptions)
```

**Comment by JupiterJones** [comment]
My own stupid mistake looking at the Xcode debug print of the export rather than the resulting encoded string.

Closing this issue.

**Comment by 3lvis** [comment]
I'm glad you got it working, @JupiterJones <3
