### ISSUE TITLE
Module compiled with Swift 4.0.3 cannot be imported in Swift 4.1

### ISSUE THREAD

**Issue by Lio1986** [3lvis/Sync#492]
Hello @3lvis ,

I updated to the latest Xcode 9.3 version and now I keep getting following error:

> Module compiled with Swift 4.0.3 cannot be imported in Swift 4.1: /.../Sync.framework/Modules/Sync.swiftmodule/arm64.swiftmodule

I already updated the settings in Preferences -> Locations -> Command Line Tools but still not working.

**Comment by 3lvis** [comment]
Fixed in the latest version, sorry for the delay :)

https://github.com/3lvis/Sync/releases/tag/4.1.3
