### ISSUE TITLE
fresh installation error

### ISSUE THREAD

**Issue by siempay** [3lvis/Sync#495]
I just installed 4.1.3 and got this 
is it my swift version ? 
![capture d ecran 2018-04-10 a 15 55 12](https://user-images.githubusercontent.com/14646888/38564868-ebb39d1a-3cd7-11e8-8bfb-a0725fa31ba0.png)

**Comment by 3lvis** [comment]
That is quite strange, might be some derived data or CocoaPods caching issue.

**Comment by gabzsa** [comment]
Same problem.

**Comment by 3lvis** [comment]
Works fine for me, did a fresh install and everything seems to be working.

https://github.com/3lvis/Sync/pull/529
