### ISSUE TITLE
Self reference relationship

### ISSUE THREAD

**Issue by pgawlowski** [3lvis/Sync#496]
Hello @3lvis,

Sync problems once again. This time relationship is like you can see here
<img width="193" alt="screen shot 2018-04-12 at 20 41 48" src="https://user-images.githubusercontent.com/9845024/38697353-0755a3b8-3e92-11e8-811d-cf24e48b2f1e.png">
<img width="257" alt="screen shot 2018-04-12 at 20 41 51" src="https://user-images.githubusercontent.com/9845024/38697361-0a536a1e-3e92-11e8-816a-b13ce52c535f.png">

Is it possible to handle with sync? So far it is creating top level object and no subcategories :(

**Comment by 3lvis** [comment]
Hi @pgawlowski,

Can you help me with a unit test? Thanks for your time :)

**Comment by pgawlowski** [comment]
@3lvis What exactly you're expecting from my side? I can prepare sample JSON, rest of settings are right on the screens :) Let me know about details, I will prepare ASAP.

**Comment by 3lvis** [comment]
Send me a sample JSON, I can set up the rest of the test :)

**Comment by pgawlowski** [comment]
It an be like that 

`{
  "id": "106",
  "name": "Components",
  "url": "/categories/106",
  "subcategories": [
    {
      "id": "816",
      "name": "Power Supplies",
      "url": "/categories/816",
      "subcategories": [
        {
          "id": "814",
          "name": "Rechargeable Batteries",
          "url": "/categories/814",
          "subcategories": [
            
          ]
        },
        {
          "id": "827",
          "name": "Power Adapters & Inverters",
          "url": "/categories/827",
          "subcategories": [
            
          ]
        },
        {
          "id": "829",
          "name": "Battery Chargers",
          "url": "/categories/829",
          "subcategories": [
            
          ]
        }
      ]
    }
  ]
}`

**Comment by pgawlowski** [comment]
@3lvis Found the reason. Somehow we forgot to use:
insertRelationships, updateRelationships
+ parent reference

**Comment by 3lvis** [comment]
I'm glad you found the problem 👏
