### ISSUE TITLE
Simple One-To-Many relationship not working

### ISSUE THREAD

**Issue by TonyNikolov** [3lvis/Sync#497]
I have simple relationship of Human to Pets. The Human object is always saved, but the pet objects never. If i change the relationship to one-to-one, its working fine. Here are the models and the actual objects i use to test.
[actual objects](https://gist.github.com/TonyNikolov/acb3a20b99186803fbe57240eaf19733)
![sync](https://user-images.githubusercontent.com/16781124/38734131-1cd710aa-3f2d-11e8-9507-5872bbd24b4f.png)

**Comment by bonebox** [comment]
I'm having the same issue. It seems to have been introduced somewhere between versions `4.0.3` and `4.1.3`.  It was working fine with `4.0.3` and have the issue after updating to `4.1.3`.  Reverting to `4.0.3` fixes it again.

**Comment by 3lvis** [comment]
Thanks for reporting 🤦‍♂️!

**Comment by schwuk** [comment]
This was affecting our project as well, and downgrading has resolved the issue. Will try and dig deeper.

**Comment by Konrad77** [comment]
Tried latest version (4.2.1) but one to many doesn't work in that version. Downgraded to 4.0.3 again and it worked like a charm.

**Comment by rebe1one** [comment]
Looks like in the [4.1.0](https://github.com/3lvis/Sync/releases/tag/4.1.0) some specific relationship options were added, and @TonyNikolov you're syncing with only [.insert, .update] but you need to add .insertRelationships and .updateRelationships as well in order for the entities to be properly linked.

**Comment by 3lvis** [comment]
I can see how that should have been a breaking change. My bad.

**Comment by 3lvis** [comment]
I know it's a bit late but I think it's the right thing to do. If you update to 4.3.0 you'll get the same functionality as before 4.1.0 plus all the bug fixes that happened after this.

If you want the new functionality you'll have to jump to 5.0.0.

# Release notes for 4.3.0
https://github.com/3lvis/Sync/releases/tag/4.3.0

# Release notes for 5.0.0 
https://github.com/3lvis/Sync/releases/tag/5.0.0

**Comment by 3lvis** [comment]
Closing for now, let me know if this is still an issue.
