### ISSUE TITLE
Question - Using Sync in my production app

### ISSUE THREAD

**Issue by BrenoVin** [3lvis/Sync#498]
Hi, I have an app which I already use core data without sync, I manage the CoreData data by myself, and now I'm thinking to use Sync. There's any problem ?!

**Comment by 3lvis** [comment]
Hi @BrenoVin,

Should be completely compatible. :) I can see how using Sync in your project would provide a battle tested, unit tested solution and you'll get to remove a bunch of code :)

**Comment by 3lvis** [comment]
Closing for now, let me know if this is still an issue.
