### ISSUE TITLE
localPrimaryKey crash.

### ISSUE THREAD

**Issue by montechristof** [3lvis/Sync#501]
Thank you for the great library. I seem to have found myself in a sort of a pickle. Upon syncing Sync generates a crash(see image). However as far as i can tell, the Managed Object that is getting parsed has an id(which i also set in user info as primary key to eliminate all the possibilities). Could you please advise how to fix this issue?
![screen shot 2018-05-02 at 12 00 27](https://user-images.githubusercontent.com/8916219/39520001-e1830e5e-4e00-11e8-98ac-f7ddb3c9cc7a.png)

**Comment by montechristof** [comment]
Hi @3lvis,
I'll cook up a uni test when i get have time, however this behaviour does not happen if i delete the app from the phone, and reinstall it. The JSON data is the same in both cases, the only possible difference is that no Measure(the entity it crashes on) in core data prior to syncing. This leads me to believe that there is a problem with my model/contexts

**Comment by montechristof** [comment]
Issue was fixed by adding a discardable value to the primaryKey.
Please close and delete.

**Comment by 3lvis** [comment]
👏
