### ISSUE TITLE
ExportOption to skip serializing null columns

### ISSUE THREAD

**Issue by Arvoreniad** [3lvis/Sync#503]
Hi! Love this project, it's been very helpful for streamlining the serialization process in our iOS app. 

An issue we've encountered is that a few of our models have a number of columns that may be null in certain cases, and we would like to avoid serializing these if they have no value. As far as I can see in the docs (forgive me if I've overlooked it), there isn't a feature that caters to this. 

It's not a significant issue at the moment, as we can simply post-process and strip null fields from the output where needed. However, this isn't ideal when processing large trees of data, and I believe it would be a useful export option in a range of cases to be able to skip null values in the output. If it fits with the vision for the project, I'd like to request it as a feature.

I would be happy to submit a PR implementing this myself if I can carve out the time in the next few weeks.

**Comment by 3lvis** [comment]
Hi @Arvoreniad,

Sorry for the realllllyyyy long wait, but yes, I think this is something we could actually do, I'll close the PR for now if you are still interested on it, I'll be happy to revisit.

**Comment by markst** [comment]
I'd also like this as an option. Is there any update on this feature?
Happy to contribute.
