### ISSUE TITLE
export() should encode NSURL in the Core Data Model as String

### ISSUE THREAD

**Issue by agottardo** [3lvis/Sync#507]
I just started using Sync a couple hours ago and I already love it. Keeping this in mind, maybe this issue is not really an issue, and I'm simply using the library in the wrong way.

At [WWDC 2017](https://developer.apple.com/videos/play/wwdc2017/210/), CoreData gained support for URI types (NSURL). I'm now using this feature in my app, instead of storing URLs as Strings as I traditionally used to do. I'm currently implementing Sync for the first time, and I have realised that if I call the `export()` function on an object containing an URL field, the `[String:Any]` dictionary that is returned seems to maintain URLs encoded as NSURL.

Wouldn't it make more sense to have `export()` serialise NSURL as Strings, maybe using the `absoluteString` property of NSURL? Just saying this because if I ask for the JSON dictionary, I would generally expect it to contain Strings or other values that are already "ready for JSON" and can readily fed to a JSON encoder. For instance, the JSONEncoder contained in Alamofire crashes when it gets passed an NSURL inside the `parameters` dictionary.

**Comment by 3lvis** [comment]
I believe this was fixed as in 4.2.0: https://github.com/3lvis/Sync/releases/tag/4.2.0

**Comment by agottardo** [comment]
Yes, indeed. Thanks!
