### ISSUE TITLE
Problem with UUID in Core Data Model

### ISSUE THREAD

**Issue by allemattio** [3lvis/Sync#508]
Hi

I'm using Sync in my app.
With XCode 9.2 everything was(and is still) working fine, but since XCode 9.3 the same code, without edits, crashes.

I don't know if its XCode 9.3 or swift 4.2 that is causing the issue.

The latest XCode update(9.3) introduced some new types for the fields, including UUID.
I was using an uuid in some of my models, and the entities with uuids cannot be synced using Sync, the uuids on the models are always empty, causing the CoreData validation to fail.

Am I the only one with this issue?
I've tried the latest version of SyncDB

**Comment by Proper-Job** [comment]
Hi @allemattio 
Are you aware of the [acronym normalization](https://github.com/3lvis/Sync#attribute-mapping).
What is your CoreData  entity's property name?

**Comment by allemattio** [comment]
Hi @Proper-Job 
Thanks,
My entity field name is uuid and is the same as the key of the json that I'm trying to sync.
I'm aware of the hyper.remoteKey property and I'm using it in other fields, but this not seems to be the problem here.
Debugging I've found that the value from the JSON is found, but Sync is unable to valorize the field on the Core Data entity in order to persist it.

As I've said, the same code compiled with XCode 9.2 is working and with XCode 9.3 is not working.

I found out that seems to be failing the mapping of the uuids values..but I can't understand why, maybe it's a problem in Sync with the new Swift or the new XCode but I don't know.
I've been working on this problem the last two weeks without success.

**Comment by palla89** [comment]
Hi, I'm in the same working team of @allemattio and I'd like to add some details to the problem:

If we try with Xcode 9.2 in the NSManagedObject+SYNCPropertyMapperHelpers.m, the attributedClass for the key "uuid" (which is a String in our CoreData Model) 

`Class attributedClass = NSClassFromString([attributeDescription attributeValueClassName]);`

returns NSString (correct). If I run the same exact project with XCode 9.3 and up, it returns nil.

So I made a brutal check on the "uuid" key to fix the error and set the Class to NSString in that case. The value now correctly sets up BUT after that, when SYNC calls context.save() the app crashes with a strange `[__NSArray0 bytes]: unrecognized selector sent to instance` without any other hint. I don't really know where to start. Can you give us some help?

**Comment by 3lvis** [comment]
Should be working now https://github.com/3lvis/Sync/pull/511

**Comment by 3lvis** [comment]
:)

**Comment by 3lvis** [comment]
Thanks for your patience and let me know how it goes 🔥

**Comment by palla89** [comment]
Hi! Sorry for the delay. We tried now the fix but unfortunately the result is maybe worse than before xD
Now it doesn't works also in 9.2, when I check the result after the hyp_fill function, the 'uuid' in 9.2 is now uuid = "(...not nil..)" and then It crashes (before it worked) while if I try on newer XCode version, the uuid after the hyp_fill is just nil once again :(

We really can't understand what is the problem!

**Comment by palla89** [comment]
I think the problem could be in this piece of code:

```
- (id)valueForAttributeDescription:(NSAttributeDescription *)attributeDescription
                  usingRemoteValue:(id)remoteValue {
    id value;

    Class attributedClass = NSClassFromString([attributeDescription attributeValueClassName]);

    if ([remoteValue isKindOfClass:attributedClass]) {
        value = remoteValue;
    }
....
}
```

The variable attributedClass is still nil when try to read uuid class.
This code is in "NSManagedObject+PropertyMapperHelpers.m" file.

Hope this helps to resolve the issue.

Thank you!

**Comment by 3lvis** [comment]
Hi Alberto!

It works fine in the unit tests so there might be something different in your scenario. Could you check the unit tests added in https://github.com/3lvis/Sync/pull/511/files or if possible, isolate your issue so I can find what the problem is?

**Comment by palla89** [comment]
We'll try to isolate the issue and let you know, but we are really struggling to understand why it used to work with the 9.2 flawlessly and with the minor 9.3 Xcode upgrade, without any other code change, it stopped to work. It's really a mystery to us

**Comment by 3lvis** [comment]
What about Xcode 9.4?

**Comment by palla89** [comment]
Same thing with 9.4 :(

**Comment by 3lvis** [comment]
Closing for lack of feedback.
