### ISSUE TITLE
Taking Coredata related operations off main thread

### ISSUE THREAD

**Issue by saraseif** [3lvis/Sync#509]
Hello guys!

According to best practices, it is better to do heavy Coredata operations in the background, not to cause any possible performance drops, or UI blocks.

I feel like you are doing some database access in the main thread:
Class: Helper, function: fetchEntity, is calling displayBlogSelector which is fetching an object from mainContext
Class: Fetcher, function: fetchLocalUsers

and also in many of the test files such as:
Class: Tests, function: testRequestWithDictionaryResultType

Don't you think it would be better to take these operations off the main thread?

**Comment by 3lvis** [comment]
Hi @saraseif!

My recommendation is *never* do calls from the main thread. Another recommendation is: use NSFetchedResultsController when possible. I've got a nice wrapper that should simplify things. https://github.com/3lvis/datasource

Let me know if I can clarify anything and have a great day! :)

**Comment by 3lvis** [comment]
Closing since the issue appears to be resolved.
