### ISSUE TITLE
Sync is syncing but does nothing

### ISSUE THREAD

**Issue by mariusschoenefeld** [3lvis/Sync#510]
I guess configured everything like in the guide, but sync won't actually sync my data.

```
[
    {
        "vehicleTypeId": 1,
        "title": "ETU",
```

I attached my Core data model.

The code I am using is this: 

```
func parseJSONToCoreData(jsonData: Any?, name: String){
        if let jsonObject = jsonData, let jsonDict = jsonObject as? [[String: Any]] {
            dataStack.sync(jsonDict, inEntityNamed: name) { error in
                print(VehicleType.mr_findFirst())
            }
        }
}
```

Its printing an empty array.

**Comment by 3lvis** [comment]
Hi @mariusschoenefeld,

My guess is that the primary key hasn't been configured properly. Check the PrimaryKey section on the README for more information: https://github.com/3lvis/Sync#primary-key

Let me know if this doesn't solve your problem and I'll dig into it.

**Comment by mariusschoenefeld** [comment]
Hey  @3lvis,

sorry for the delay. I think I configured everything right. I added my data model below:
![bildschirmfoto 2018-06-08 um 16 07 09](https://user-images.githubusercontent.com/17689671/41349182-5b93781c-6f0f-11e8-9712-0777917f9793.png)

**Comment by patriksharma** [comment]
same happening to me. its coming NIL , did you find any solution @mariusschoenefeld

**Comment by arrchhy** [comment]
this is frustrating. Error is nil though nothing is written into Core Data.

**Comment by patriksharma** [comment]
@arrchhy I have solved it. You need to set sync.remotekey as suggested above. Make sure your remote key name should be same as coming from API

**Comment by arrchhy** [comment]
Okay I solved it by reading the demo source. the context in sync is `self.dataStack.viewContext` and not the one you normally set up in your app delegate. would have been nice to mention this in readme.

**Comment by 3lvis** [comment]
Hi @arrchhy! Looks like your issue was different than the remote key. Could you expand a bit so I can add it to the README?

Thanks 🙏

**Comment by arrchhy** [comment]
@3lvis oh I was just using the wrong viewContext. I had had already a coredata layer in the app (initalised in app delegate). I had the misconception that Sync shared the same context as my existing core data layer.

**Comment by arrchhy** [comment]
@3lvis By the way thanks man for such awesome library! 💪💪💪💪 
It's super good  👍

**Comment by 3lvis** [comment]
I see! I'm glad you got it working. Have an epic weekend 🎉
