### ISSUE TITLE
No update with operations

### ISSUE THREAD

**Issue by MattiasBurstrom** [3lvis/Sync#520]
I'm not seeing any updates when specifying only [.insert, .update] operations. When calling to just sync entity with the array of data it deletes everything and insert the new ones... so if I call for a subset of data from the remote and just want to update the existing records and keep the rest, it deletes everything and only the subset is inserted. How can I update just some records and keep the rest?

I see it works to update using insertOrUpdate instead but shouldn't it work to specify the operations as well?

**Comment by 3lvis** [comment]
Hi! I think the issue could be related that now there's

```swift
[.insert, .update, .delete, .insertRelationships, .updateRelationships, .deleteRelationships]
```

**Comment by 3lvis** [comment]
Closing for lack of feedback.

**Comment by bilics** [comment]
Hi! 

How do I use these options with Objective C ?

Thanks!

**Comment by 3lvis** [comment]
@bilics We don't have Objective-C support for that, but you can create a Swift extension for your class and have the Swift method there, then it will work fine :)

**Comment by bilics** [comment]
Thanks @3lvis!

I am kinda new to this... can you give me some pointers or tutorials so I can dig through ?

Thanks again

**Comment by 3lvis** [comment]
Mmm, I don't know if any tutorials for this but..

MyClass.m

```objc
#import "MyProject-Swift.h" // This header is autogenerated and it usually goes as "TargetName-Swift

- (void)doSomethingInObjectiveC {
    [self callSwiftMethod];
}
```

### MyClass.swift
```swift
import Sync

extension MyClass {    
    func callSwiftMethod() {
        // Use Swift
    }
}
```

**Comment by bilics** [comment]
Thanks!! I will go from here and post back if I find any problems.
