### ISSUE TITLE
Crashing on Exporting model having a To-Many relationship 

### ISSUE THREAD

**Issue by himanshuNetsol** [3lvis/Sync#524]
I have two Core Data models, having To-Many relationship and inverse relation as well. Whenever, im trying to export the model, its getting crashed. Can u pls help me out with this?
Thanks
![screen shot 2018-08-01 at 2 45 12 am](https://user-images.githubusercontent.com/37396038/43487948-ccedcab6-9535-11e8-8201-184e99c30271.png)

**Comment by 3lvis** [comment]
Hi! Could you please share your data model and your JSON so I can reproduce the issue?

**Comment by himanshuNetsol** [comment]
Hi, Can u please share ur email id so that i can share resources with u??
Thanks

**Comment by 3lvis** [comment]
@himanshuNetsol elvisnunez@me.com

**Comment by 3lvis** [comment]
Got your files! I'll look into it when I get some time :)

**Comment by himanshuNetsol** [comment]
Sure.. Thanks

**Comment by fshbn** [comment]
Same here.

**Comment by 3lvis** [comment]
Damn.

**Comment by 3lvis** [comment]
I'll try to set some time aside today to get to the bottom of this.

**Comment by himanshuNetsol** [comment]
Also, when im trying to sync large batch of data using  **dataStack.sync** , data  to-many relationship is not getting saved in the database. Only the data in master table is getting inserted. Im using these options : 
        dataStack.sync(dataArray, inEntityNamed: table.rawValue, operations: [.insert, .update, .insertRelationships, .updateRelationships])
But, when i make an entry with  dataStack.insertOrUpdate, the data is getting inserted into the relationship tables.
For refrence, u can use the same json i've emailed u.
Can u also help me out with that??

**Comment by himanshuNetsol** [comment]
@3lvis . Can i get any possible help on above? :-)

**Comment by 3lvis** [comment]
@himanshuNetsol From your model I can see two things, your relationship is called "cakeOrder" but is a to-many, should it be a to-one? Also you are using "customerId", "storeLocationId" and so on when Sync expects "customerID" and  "storeLocationID" for example. "ID" instead of "Id".

**Comment by himanshuNetsol** [comment]
hi @3lvis , Thanks for u time and reply. Yes, agree, But i'm using **sync.remoteKey** for all those cases , and providing their respective remote keys . Should'nt it make a difference??

**Comment by himanshuNetsol** [comment]
And, cakeOrder in an array , and should'nt it be a to-many relationship?

**Comment by 3lvis** [comment]
Changed orderId to just id and seems like it works https://github.com/3lvis/Sync/pull/525

**Comment by 3lvis** [comment]
<img width="494" alt="screen shot 2018-08-10 at 09 59 59" src="https://user-images.githubusercontent.com/1088217/43945969-26c75cf0-9c84-11e8-9849-83e5853415fe.png">

**Comment by 3lvis** [comment]
@fshbn Could you please make a separate issue with your JSON file and Core Data model to see if I can reproduce it?

**Comment by 3lvis** [comment]
@himanshuNetsol Hi, I'm having a hard time reproducing your issue, I'm going to need an isolated project so I can inspect the problem. Could you help me with that?

**Comment by himanshuNetsol** [comment]
Hi @3lvis , It worked on Changing the name from orderId to Id. Also, i've to change the relationShip table's primary key name from rawCakeId to id. The Relationship is getting filling up. Haven't tested export() though after changing.

**Comment by 3lvis** [comment]
@himanshuNetsol that's good news!

**Comment by himanshuNetsol** [comment]
Yeah.. Indeed .. Thanks to you.. Also, i'll get back to u after completely testing export()

**Comment by 3lvis** [comment]
🎉
