### ISSUE TITLE
How to fetch complete list of data from Any Table(Entity)

### ISSUE THREAD

**Issue by aman198** [3lvis/Sync#526]
s
This the code what we are using to fetch specific id Data.

 let value =   try self.appDelegate.dackStack.fetch(6, inEntityNamed: "User")
 We want to fetch all data inside that Table ("User")

**Comment by 3lvis** [comment]
The fetch method is properly documented but you could also check the FetchTests for an idea on how to use it.

<img width="541" alt="screen shot 2018-08-23 at 23 33 00" src="https://user-images.githubusercontent.com/1088217/44553154-e4926880-a72c-11e8-82e7-e636c999633c.png">


https://github.com/3lvis/Sync/blob/master/Tests/Sync/FetchTests.swift

**Comment by 3lvis** [comment]
Closing for now, let me know if this is still an issue.

___
###### Like Sync? Don't forget to support this and other projects in [Patreon](https://www.patreon.com/3lvis)!
