### ISSUE TITLE
Usage, how to

### ISSUE THREAD

**Issue by DennisKragekjaer** [3lvis/Sync#530]
Hi. 

Im new to Sync, love Sync, and all seemed to work fine for my use case, but then my use case changed to this:

User logs in, getting data from server and mapping to core data model, all good. He then changes som data, and then maybe log out.

He later logs in again, getting data from server again.

I'm a little confused on how to use Sync in this scenarium: I want to keep the old changes of data and not overwriting them with the new data from the server, but still want if data is added to the serverdata.

**Getting data first time:**
API.shared.dataStack.sync(usersJSON, inEntityNamed:  "VisitGroup") { error in.....

**Tried this afterwards:**
Sync.changes(json, inEntityNamed: "VisitGroup", dataStack: API.shared.dataStack, operations: [.update, completion:......

What is the right way to do this?

**Comment by 3lvis** [comment]
Sorry for not replying before Dennis, I hope you figure it out.
