### ISSUE TITLE
Relationship set returns empty

### ISSUE THREAD

**Issue by ourdex86** [3lvis/Sync#555]
I have created two Entities **Employee** & **Course**. And, I have a One-To-Many relationship call **courses**.

Here is my JSON  : 

`[{"name":"John","age":21,"courses":[{"courseName":"Computers","courseId":506},{"courseName":"Electronics","courseId":507}]}]
`

```
let dataStack = DataStack(modelName: "LibrariesDemo")        
        dataStack.sync(jsonArray, inEntityNamed: "Employee") { (error) in
            let employees = try! dataStack.viewContext.fetch(Employee.fetchRequest()) as! [Employee]
            print("Courses Count = \(employees.last?.courses.count)")
        }
```
With the above implementation, **courses**  is always returning empty

**Comment by 3lvis** [comment]
Strange, @ourdex86 do you still need help?

**Comment by ourdex86** [comment]
Yes, I still didn't find the solution

**Comment by ali-ehsan** [comment]
Same issue

**Comment by ourdex86** [comment]
@3lvis .. Are you checking this issue ?? :(

**Comment by 3lvis** [comment]
Hi @ourdex86!

Looking at it now

**Comment by 3lvis** [comment]
Hi @ourdex86 @ali-ehsan,

There must be something strange in your implementation, I gave it a try and it works fine. 😕

**Comment by 3lvis** [comment]
https://github.com/3lvis/Sync/pull/561

**Comment by 3lvis** [comment]
Restaurant Jensens Bøfhus Oslo
Stortingsgata 2, 0158 Oslo, Norway
+47 406 90 680
https://goo.gl/maps/u5uPsCBB6pkApMPn6

**Comment by 3lvis** [comment]
Thanks for your support in this library. It has been a while since I used CoreData in any of my projects and it's hard for me to maintain this library. If you have been part of the Sync contributors group and want to take ownership of the library let me know to elvisnunez@me.com. For now, I'll be archiving this library.
