### ISSUE TITLE
Publish 5.2.1 to Cocoapods

### ISSUE THREAD

**Issue by joeboyscout04** [3lvis/Sync#556]
Is it possible to publish the latest release to the Cocoapods master repo?  It's still sitting at 5.1.0 there.  Thanks,

**Comment by 3lvis** [comment]
Damn, sorry! new version coming.

**Comment by ali-ehsan** [comment]
When are you going to push the latest version?

**Comment by 3lvis** [comment]
I was having some issues with my computer but now I have released the Swift 5 version.

https://github.com/3lvis/Sync/releases/tag/6.0.0
