### ISSUE TITLE
Swift 5 / Xcode 10.2 support

### ISSUE THREAD

**Issue by tbechtum** [3lvis/Sync#558]
Hi,
Swift 5 compiler produces 32 new Xcode 10.2 warning issues which should and can be easily resolved: e.g.
/Developer/Cockpit/Pods/Sync/Source/Sync/Sync+DataStack.swift:11:5: 'public' modifier is redundant for instance method declared in a public extension
RESOLVE: public function modifier should be removed in these cases.
Thanks.

**Comment by 3lvis** [comment]
Done!

**Comment by tbechtum** [comment]
Installed Sync 6.0.0 (was 5.1.0) and all Xcode warnings disappeared. Thank you for time and effort!

**Comment by 3lvis** [comment]
You're very welcome :)
