### ISSUE TITLE
Relationship data not saving when insert/update operations added

### ISSUE THREAD

**Issue by kvnh** [3lvis/Sync#563]
I appear to be having issues saving relationship data when `operations: [.insert, .update]` is set in the arguments.

Top level attributes like id and name save no problem but Question objects do not save.
When I remove the operations argument, the questions list will save successfully. But I need to use the insert/update operation. Has anyone else seen this issue?

`
{
    id = 4875;
    name = "1_template";
    questions =     (
                {
            id = 234555999;
            identifier = "1.1";
        },
                {
            id = 234555999;
            identifier = "1.2";
        },
                {
            id = 234555999;
            identifier = "1.3";
        }
    );
    version = 17;
}
`

I am using the latest 6.0.0 pod

**Comment by kvnh** [comment]
Duplicate of https://github.com/3lvis/Sync/issues/520
I needed to add .insertRelationships, .updateRelationships to the operations arg

**Comment by 3lvis** [comment]
Happy that you got this resolved ❤️
