### ISSUE TITLE
insertOrUpdate doesn't update null values

### ISSUE THREAD

**Issue by dansinclair25** [3lvis/Sync#567]
Given you've already stored a value against a property, when you try to `insertOrUpdate` the object but that value is `null` then it doesn't work and doesn't store the value of `null`.

I think this is because the DataStack's `insertOrUpdate` function requires a non-optional valued dictionary (`[String: Any]`) so it will "strip out" any nil objects.

**Comment by dansinclair25** [comment]
To update, I see there's this [issue](https://github.com/3lvis/Sync/issues/255) which is similar and in it you say
> To be clear, the way to nullify an item would be by sending null in JSON
That's what we're doing but it's not nullifying the object.

**Comment by 3lvis** [comment]
Hi Dan, it's been a while since I worked on this issue. To clarify, you want 

```json
{
  turned_on: null
}
```

to use the default value instead of `null`?

**Comment by dansinclair25** [comment]
Hi @3lvis,

Don't worry - it appears it's my issue all along…

My use case means I don't pass serialized JSON directly to Sync. I decode into an object, and then have a custom function to turn the object into a `[String: Any]` dictionary, but the way I was creating the dictionary meant `nil` values were never passed along…

Closing the ticket!

**Comment by 3lvis** [comment]
Noted! Let me know if I can help with anything else :)
