### ISSUE TITLE
Swift Package Manager support

### ISSUE THREAD

**Issue by whoyawn** [3lvis/Sync#569]
Is this still being maintained? Would love to see if this is SPM-compatible.

**Comment by 3lvis** [comment]
Hi @whoyawn, 

That's a good question, it should be since we don't have any assets. Feel free to add support. Happy to merge it :)

**Comment by Schaefers** [comment]
I created a fork and added a `Package.swift` file, but when importing the Package into one of my projects, I get this error message: 

```
/Users/user/Library/Developer/Xcode/DerivedData/App-geedamhpasuncxeweflbiscehzkj/SourcePackages/checkouts/Package.swift: target at '/Users/user/Library/Developer/Xcode/DerivedData/App-geedamhpasuncxeweflbiscehzkj/SourcePackages/checkouts/Source' contains mixed language source files; feature not supported
```

There is a detailed explanation in the swift forums, but the provided link isn't working and I couldn't find it in the SPM documentation.

https://forums.swift.org/t/spm-library-with-bridging-header/4945

**Comment by kaishin** [comment]
SPM does not support mixed source libraries. I tried creating two targets, `Sync` and `SyncObjC` but it wasn't trivial to get it to work while still making sure that it continues to work  without SPM.

**Comment by 3lvis** [comment]
@kaishin I think we might have to rewrite all the ObjC parts into Swift. 🤦‍♂

**Comment by 3lvis** [comment]
Thanks for your support in this library. It has been a while since I used CoreData in any of my projects and it's hard for me to maintain this library. If you have been part of the Sync contributors group and want to take ownership of the library let me know to elvisnunez@me.com. For now, I'll be archiving this library.
