### ISSUE TITLE
can't export many to many relationship

### ISSUE THREAD

**Issue by fatbobman** [3lvis/Sync#574]
I try using sync for my project .
there is three entitys in my test.
classroom 
student 
teacher

classroom  --- one to many  --- student 
student ---- one to one --- classroom

After adding some sample datas , export classroom , everything run well.

classroom --- many to many ---- teacher
teacher --- many to many ---- classroom

After adding data in teacher , export classroom , app crush immediately .

Program will get stuck at  
```
- (NSString *)remotePrefixUsingInflectionType:(SyncPropertyMapperInflectionType)inflectionType {
    switch (inflectionType) {
        case SyncPropertyMapperInflectionTypeSnakeCase:
            return [NSString stringWithFormat:@"%@_", [self.entity.name hyp_snakeCase]];     //this line!
            break;
        case SyncPropertyMapperInflectionTypeCamelCase:
            return [self.entity.name hyp_camelCase];
            break;
    }
}
```   

then I try to user camelCase type 
exportOptions.inflectionType = .camelCase

Program will get stuck at  
```
- (void)performOnDictionary:(InflectionsStringStorageBlock)block {
	dispatch_sync(_serialQueue, block);   //this line!

}
```

What am i doing wrong？
Thanks.

**Comment by 3lvis** [comment]
Thanks for your support in this library. It has been a while since I used CoreData in any of my projects and it's hard for me to maintain this library. If you have been part of the Sync contributors group and want to take ownership of the library let me know to elvisnunez@me.com. For now, I'll be archiving this library.
