### ISSUE TITLE
JSON data cannot convert to [[String:Any]]

### ISSUE THREAD

**Issue by brhoomjs** [3lvis/Sync#575]
Hello there am so thankful for your awesome job in this repo, this is my first time using it. 
I an issue to sync some data
I tried by Alamofire, Networking and even from local JSON File.
the problem is I think to use this JSON as [[String:Any]]
here's the JSON content from the API and local file.
`{
    "id": 377,
    "fullname": "Francisco larrere",
    "avatar": "default.png",
    "country": "AR",
    "phone": 54200000000,
    "email": "franci****@hotmail.com",
    "horses": [
        {
            "id": 103,
            "gender": 4,
            "type": 0,
            "sold": 0,
            "image": "5e42d06168f61-103.jpg"
        },
        {
            "id": 102,
            "gender": 4,
            "type": 0,
            "sold": 0,
            "image": "5e42cfd8b7c94-102.jpg"
        }
    "privateHorses": []
}
`
and here's my model:
<img width="300" alt="Screen Shot 2020-04-08 at 6 30 53 AM" src="https://user-images.githubusercontent.com/12615977/78738312-96ae9080-7962-11ea-9eea-6e08806c60a8.png">
<img width="300" alt="Screen Shot 2020-04-08 at 6 31 13 AM" src="https://user-images.githubusercontent.com/12615977/78738318-9910ea80-7962-11ea-8887-e331dca87e57.png">

and my code:
*Local*
<img width="1066" alt="Screen Shot 2020-04-08 at 6 35 36 AM" src="https://user-images.githubusercontent.com/12615977/78738596-4b48b200-7963-11ea-854f-5df8363a1f95.png">
*Networking*
<img width="831" alt="Screen Shot 2020-04-08 at 6 36 20 AM" src="https://user-images.githubusercontent.com/12615977/78738589-471c9480-7963-11ea-98f6-5e0372ed38ba.png">

**Comment by rlester** [comment]
My initial guess without seeing the actual error message would be that the privateHorses key is not matching the name of the core data relationship (horses).

Give this a try: https://github.com/3lvis/Sync#attribute-mapping

**Comment by brhoomjs** [comment]
Thanks for your response but I what I meant is I can’t run or build the code won’t compile.

**Comment by rlester** [comment]
@brhoomjs any luck resolving this?

**Comment by brhoomjs** [comment]
> @brhoomjs any luck resolving this?

Sorry for the delay I want to rebuild my project and orgnize it. I need sometime. when I come for the networking part I'll reply here.

**Comment by 3lvis** [comment]
Closing this, hopefully @brhoomjs found the issue. And sorry for the delay!
