### ISSUE TITLE
Module compiled with Swift 5.1.3 cannot be imported by the Swift 5.2 compiler

### ISSUE THREAD

**Issue by brandonpark** [3lvis/Sync#576]
Hello @3lvis ,

With the latest Xcode I am getting the following error

`Module compiled with Swift 5.1.3 cannot be imported by the Swift 5.2 compiler: /Users/brandonmccandlish/Downloads/Sync-master/iOSDemo/Carthage/Build/iOS/Sync.framework/Modules/Sync.swiftmodule/x86_64.swiftmodule`

Any chance on an update for Swift 5.2?

**Comment by olopsman** [comment]
Running on Xcode 11.5 and the same issue.

Module compiled with Swift 5.1.3 cannot be imported by the Swift 5.2.4 compiler: 

`/Users/PauloOrquilo/Documents/Development/Mobile/Training/CoreData/Sync/iOSDemo/Carthage/Build/iOS/Sync.framework/Modules/Sync.swiftmodule/x86_64.swiftmodule`

**Comment by olopsman** [comment]
> Running on Xcode 11.5 and the same issue.
> 
> Module compiled with Swift 5.1.3 cannot be imported by the Swift 5.2.4 compiler:
> 
> `/Users/PauloOrquilo/Documents/Development/Mobile/Training/CoreData/Sync/iOSDemo/Carthage/Build/iOS/Sync.framework/Modules/Sync.swiftmodule/x86_64.swiftmodule`

I was able to resolve this by deleting the current frameworks in the project and rebuilding it. From the terminal go Cartfile location and run:

`carthage update --platform IOS`

**Comment by 3lvis** [comment]
Should be fixed in the latest release, if the problem persists please let me know.

**Comment by 3lvis** [comment]
I'm glad you got a fix for this, thanks for sharing @badmunkey
