### ISSUE TITLE
FailureJSONResponse

### ISSUE THREAD

**Issue by badmunkey** [3lvis/Sync#580]
I copied your syncAlamofire code from your project to my project.
I am seeing this error  on line 69
Cannot convert value of type 'NSError' to expected argument type 'FailureJSONResponse'

60   func syncTypeUsingAlamofire(completion: @escaping (_ result: VoidResult) -> ()) {
61       Alamofire.request("http://dafounders.com/esogearcopytype.php").responseJSON { response in
62            if let jsonObject = response.result.value, let gearTypeJSON = jsonObject as? [[String: Any]] {
63                self.dataStack.sync(gearTypeJSON, inEntityNamed: GearType.entity().name!) { error in
64                    completion(.success)
65                
66
67                }
68   } else if let error = response.error {
69                    completion(.failure(error as NSError))
70               } else {
71                    fatalError("No error, no failure")
72                }

**Comment by badmunkey** [comment]
NVM I figured it out. I see now that I did not include the ENUMS you had stated below in your Fetcher.swift file

**Comment by 3lvis** [comment]
I'm glad you got it working
