### ISSUE TITLE
Application crash on NSManagedObject model.export() 

### ISSUE THREAD

**Issue by DemetAkyol** [3lvis/Sync#581]
![Screenshot at Aug 25 20-57-53](https://user-images.githubusercontent.com/42372988/91210332-b8dc5b80-e715-11ea-9964-65ef2aeb1e8c.png)

When I want to export the model, the application crashes.
error is ;
Thread 1: EXC_BAD_ACCESS (code=2, address=0x16d3dbfc0)

- (NSString *)remotePrefixUsingInflectionType:(SyncPropertyMapperInflectionType)inflectionType {
    switch (inflectionType) {
        case SyncPropertyMapperInflectionTypeSnakeCase:
            return [NSString stringWithFormat:@"%@_", [self.entity.name hyp_snakeCase]];
            break;
        case SyncPropertyMapperInflectionTypeCamelCase:
            return [self.entity.name hyp_camelCase];
            break;
    }
}

in              return [NSString stringWithFormat:@"%@_", [self.entity.name hyp_snakeCase]];

**Comment by 3lvis** [comment]
Could you share the model and an example of the data you're trying to export? 

Maybe some steps to reproduce would help a lot too.

**Comment by DemetAkyol** [comment]
extension DynamicDataConfigurationField {

    @nonobjc public class func fetchRequest() -> NSFetchRequest<DynamicDataConfigurationField> {
        return NSFetchRequest<DynamicDataConfigurationField>(entityName: "DynamicDataConfigurationField")
    }

    @NSManaged public var boundToFieldWithId: NSNumber?
    @NSManaged public var copyFromLastDynamicData: NSNumber?
    @NSManaged public var displayOrder: NSNumber?
    @NSManaged public var dynamicDataConfigurationId: NSNumber?
    @NSManaged public var dynamicDataFieldTypeId: NSNumber?
    @NSManaged public var maxValue: NSDecimalNumber?
    @NSManaged public var minValue: NSDecimalNumber?
    @NSManaged public var visibilityBoundToFieldOptionIds: String?
    @NSManaged public var defaultValue: String?
    @NSManaged public var boundToField: DynamicDataConfigurationField?
    @NSManaged public var dynamicDataConfiguration: DynamicDataConfiguration?
    @NSManaged public var dynamicDataConfigurationFieldOptions: NSSet?
    @NSManaged public var dynamicDataFields: NSSet?
    @NSManaged public var fields: NSSet?

}


class DynamicDataConfiguration: BaseEntity{
    
    internal static let PASSIVE_FIELD_NAME: String = "passive"
    internal static let DYNAMIC_DATA_CONFIGURATION_TYPE_ID_FIELD_NAME: String = "dynamicDataConfigurationTypeId"
    internal static let PRIORITY_FIELD_NAME = "priority"
    internal static let MODEL_ID = "modelId"
}


CoreDataProperties and extension

**Comment by 3lvis** [comment]
What was the name of your Entity? The one that crashed was it DynamicDataConfigurationField ?

**Comment by 3lvis** [comment]
Closing for lack of follow up
