### ISSUE TITLE
Module compiled with Swift 5.2.4 cannot be imported by the Swift 5.3 compiler

### ISSUE THREAD

**Issue by lgebing** [3lvis/Sync#584]
Hi,

after upgrading to Swift 5.3 / Xcode 12 i am getting this error:

`Module compiled with Swift 5.2.4 cannot be imported by the Swift 5.3 compiler: /Users/user/Desktop/Xcode/project/Carthage/Build/iOS/Sync.framework/Modules/Sync.swiftmodule/arm64-apple-ios.swiftmodule`

It it possible to update this so it can compile under Swift 5.3?

**Comment by lgebing** [comment]
Fixed thanks to answer in previous issue:

https://github.com/3lvis/Sync/issues/576#issuecomment-636623529

**Comment by 3lvis** [comment]
Fixed as well
